//>>built
require({cache:{"djeo-ge/Navigation":function(){define("djeo-ge/Navigation",["dojo/_base/declare"],function(d){return d(null,{enable:function(d){d===void 0&&(d=!0);this.map.engine.ge.getOptions().setMouseNavigationEnabled(d)}})})},"dojo/NodeList-dom":function(){define("dojo/NodeList-dom",["./_base/kernel","./query","./_base/array","./_base/lang","./dom-class","./dom-construct","./dom-geometry","./dom-attr","./dom-style"],function(d,j,h,e,g,f,m,l,s){function n(a){return function(b,c,d){if(arguments.length==
2)return a[typeof c=="string"?"get":"set"](b,c);return a.set(b,c,d)}}var q=function(a){return a.length==1&&typeof a[0]=="string"},p=function(a){var b=a.parentNode;b&&b.removeChild(a)},o=j.NodeList,a=o._adaptWithCondition,b=o._adaptAsForEach,c=o._adaptAsMap;e.extend(o,{_normalize:function(a,b){var c=a.parse===!0;if(typeof a.template=="string")var k=a.templateFunc||d.string&&d.string.substitute,a=k?k(a.template,a):a;k=typeof a;k=="string"||k=="number"?(a=f.toDom(a,b&&b.ownerDocument),a=a.nodeType==
11?e._toArray(a.childNodes):[a]):e.isArrayLike(a)?e.isArray(a)||(a=e._toArray(a)):a=[a];if(c)a._runParse=!0;return a},_cloneNode:function(a){return a.cloneNode(!0)},_place:function(a,b,c,e){if(!(b.nodeType!=1&&c=="only"))for(var g,h=a.length,j=h-1;j>=0;j--){var m=e?this._cloneNode(a[j]):a[j];if(a._runParse&&d.parser&&d.parser.parse){g||(g=b.ownerDocument.createElement("div"));g.appendChild(m);d.parser.parse(g);for(m=g.firstChild;g.firstChild;)g.removeChild(g.firstChild)}j==h-1?f.place(m,b,c):b.parentNode.insertBefore(m,
b);b=m}},attr:a(n(l),q),style:a(n(s),q),addClass:b(g.add),removeClass:b(g.remove),replaceClass:b(g.replace),toggleClass:b(g.toggle),empty:b(f.empty),removeAttr:b(l.remove),position:c(m.position),marginBox:c(m.getMarginBox),place:function(a,b){var c=j(a)[0];return this.forEach(function(a){f.place(a,c,b)})},orphan:function(a){return(a?j._filterResult(this,a):this).forEach(p)},adopt:function(a,b){return j(a).place(this[0],b)._stash(this)},query:function(a){if(!a)return this;var b=new o;this.map(function(c){j(a,
c).forEach(function(a){a!==void 0&&b.push(a)})});return b._stash(this)},filter:function(a){var b=arguments,c=this,d=0;if(typeof a=="string"){c=j._filterResult(this,b[0]);if(b.length==1)return c._stash(this);d=1}return this._wrap(h.filter(c,b[d],b[d+1]),this)},addContent:function(a,b){for(var a=this._normalize(a,this[0]),c=0,d;d=this[c];c++)this._place(a,d,b,c>0);return this}});return o})},"dojo/_base/loader":function(){define("dojo/_base/loader",["./kernel","../has","require","module","./json","./lang",
"./array"],function(d,j,h,e,g,f,m){var l=function(a){return a.replace(/\./g,"/")},s=/\/\/>>built/,n=[],q=[],p,o=function(a){p[a.mid]=1;for(var b,c,d=a.deps||[],i=0;i<d.length;i++)if(c=d[i],!(b=p[c.mid]))if(b===0||!o(c))return p[a.mid]=0,!1;return!0},a=function(){var a,b;p={};for(b in z)if(a=z[b],a.executed||a.noReqPluginCheck)p[b]=1;else{if(a.noReqPluginCheck!==0)a.noReqPluginCheck=/loadInit\!/.test(b)||/require\!/.test(b)?1:0;a.noReqPluginCheck?p[b]=1:a.injected!==x&&(p[b]=0)}for(var c=0,i=q.length;c<
i;c++)if(a=q[c],!(b=p[a.mid]))if(b===0||!o(a))return;k.holdIdle();a=n;n=[];m.forEach(a,function(a){a(1)});k.releaseIdle()},b=function(a,b,c){var i=/\(|\)/g,e=1;for(i.lastIndex=b;b=i.exec(a);)if(b[0]==")"?e-=1:e+=1,e==0)break;if(e!=0)throw"unmatched paren around character "+i.lastIndex+" in: "+a;return[d.trim(a.substring(c,i.lastIndex))+";\n",i.lastIndex]},c=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,i=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,
r=/(^|\s)(require|define)\s*\(/m,t=function(a,d){var e,f,g,t=[],h=[];e=[];for(d=d||a.replace(c,function(a){i.lastIndex=r.lastIndex=0;return i.test(a)||r.test(a)?"":a});e=i.exec(d);)f=i.lastIndex,g=f-e[0].length,f=b(d,f,g),e[2]=="loadInit"?t.push(f[0]):h.push(f[0]),i.lastIndex=f[1];e=t.concat(h);return e.length||!r.test(d)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 && dojo.loadInit("),e.join(""),e]:0},k=h.initSyncLoader(function(b,c,i){n.push(i);m.forEach(b.split(","),function(a){a=u(a,c.module);
q.push(a);w(a)});a()},a,function(a,b){var c,i,e=[],f=[];if(s.test(b)||!(c=t(b)))return 0;i=a.mid+"-*loadInit";for(var g in u("dojo",a).result.scopeMap)e.push(g),f.push('"'+g+'"');return"// xdomain rewrite of "+a.path+"\ndefine('"+i+"',{\n\tnames:"+d.toJson(e)+",\n\tdef:function("+e.join(",")+"){"+c[1]+"}});\n\ndefine("+d.toJson(e.concat(["dojo/loadInit!"+i]))+", function("+e.join(",")+"){\n"+c[0]+"});"}),E=k.sync,x=k.arrived,y=k.nonmodule,F=k.executing,A=k.executed,v=k.syncExecStack,z=k.modules,B=
k.execQ,u=k.getModule,w=k.injectModule,C=k.setArrived,G=k.signal,H=k.finishExec,I=k.execModule,D=k.getLegacyMode;d.provide=function(a){var b=v[0],c=f.mixin(u(l(a),h.module),{executed:F,result:f.getObject(a,!0)});C(c);if(b)(b.provides||(b.provides=[])).push(function(){c.result=f.getObject(a);delete c.provides;c.executed!==A&&H(c)});return c.result};j.add("config-publishRequireResult",1,0,0);d.require=function(a,b){var c=function(a,b){var c=u(l(a),h.module);if(v.length&&v[0].finish)v[0].finish.push(a);
else{if(c.executed)return c.result;b&&(c.result=y);var i=D();w(c);i=D();c.executed!==A&&c.injected===x&&(k.holdIdle(),I(c),k.releaseIdle());if(c.executed)return c.result;i==E?c.cjs?B.unshift(c):v.length&&(v[0].finish=[a]):B.push(c)}}(a,b);j("config-publishRequireResult")&&!f.exists(a)&&c!==void 0&&f.setObject(a,c);return c};d.loadInit=function(a){a()};d.registerModulePath=function(a,b){var c={};c[a.replace(/\./g,"/")]=b;h({paths:c})};d.platformRequire=function(a){for(var a=(a.common||[]).concat(a[d._name]||
a["default"]||[]),b;a.length;)f.isArray(b=a.shift())?d.require.apply(d,b):d.require(b)};d.requireIf=d.requireAfterIf=function(a,b,c){a&&d.require(b,c)};d.requireLocalization=function(a,b,c){h(["../i18n"],function(i){i.getLocalization(a,b,c)})};return{extractLegacyApiApplications:t,require:k.dojoRequirePlugin,loadInit:function(b,c,i){c([b],function(b){c(b.names,function(){for(var f="",g=[],r=0;r<arguments.length;r++)f+="var "+b.names[r]+"= arguments["+r+"]; ",g.push(arguments[r]);eval(f);var t=c.module,
h=[],f={},j=[],k,r={provide:function(a){a=l(a);a=u(a,t);a!==t&&C(a)},require:function(a,b){a=l(a);b&&(u(a,t).result=y);j.push(a)},requireLocalization:function(a,b,c){h.length||(h=["dojo/i18n"]);c=(c||d.locale).toLowerCase();a=l(a)+"/nls/"+(/root/i.test(c)?"":c+"/")+l(b);u(a,t).isXd&&h.push("dojo/i18n!"+a)},loadInit:function(a){a()}};try{for(k in r)f[k]=d[k],d[k]=r[k];b.def.apply(null,g)}catch(o){G("error",[{src:e.id,id:"failedDojoLoadInit"},o])}finally{for(k in r)d[k]=f[k]}j.length&&h.push("dojo/require!"+
j.join(","));n.push(i);m.forEach(j,function(a){a=u(a,c.module);q.push(a);w(a)});a()})})}}})},"dojo/io/script":function(){define("dojo/io/script",["../main"],function(d){d.getObject("io",!0,d);var j=d.isIE?"onreadystatechange":"load",h=/complete|loaded/;d.io.script={get:function(e){var g=this._makeScriptDeferred(e),f=g.ioArgs;d._ioAddQueryToUrl(f);d._ioNotifyStart(g);if(this._canAttach(f)){var m=this.attach(f.id,f.url,e.frameDoc);if(!f.jsonp&&!f.args.checkString)var l=d.connect(m,j,function(e){if(e.type==
"load"||h.test(m.readyState))d.disconnect(l),f.scriptLoaded=e})}d._ioWatch(g,this._validCheck,this._ioCheck,this._resHandle);return g},attach:function(e,g,f){var f=f||d.doc,h=f.createElement("script");h.type="text/javascript";h.src=g;h.id=e;h.async=!0;h.charset="utf-8";return f.getElementsByTagName("head")[0].appendChild(h)},remove:function(e,g){d.destroy(d.byId(e,g));this["jsonp_"+e]&&delete this["jsonp_"+e]},_makeScriptDeferred:function(e){var g=d._ioSetArgs(e,this._deferredCancel,this._deferredOk,
this._deferredError),f=g.ioArgs;f.id=d._scopeName+"IoScript"+this._counter++;f.canDelete=!1;f.jsonp=e.callbackParamName||e.jsonp;if(f.jsonp)f.query=f.query||"",f.query.length>0&&(f.query+="&"),f.query+=f.jsonp+"="+(e.frameDoc?"parent.":"")+d._scopeName+".io.script.jsonp_"+f.id+"._jsonpCallback",f.frameDoc=e.frameDoc,f.canDelete=!0,g._jsonpCallback=this._jsonpCallback,this["jsonp_"+f.id]=g;return g},_deferredCancel:function(e){e.canceled=!0;e.ioArgs.canDelete&&d.io.script._addDeadScript(e.ioArgs)},
_deferredOk:function(e){e=e.ioArgs;e.canDelete&&d.io.script._addDeadScript(e);return e.json||e.scriptLoaded||e},_deferredError:function(e,g){g.ioArgs.canDelete&&(e.dojoType=="timeout"?d.io.script.remove(g.ioArgs.id,g.ioArgs.frameDoc):d.io.script._addDeadScript(g.ioArgs));return e},_deadScripts:[],_counter:1,_addDeadScript:function(e){d.io.script._deadScripts.push({id:e.id,frameDoc:e.frameDoc});e.frameDoc=null},_validCheck:function(){var e=d.io.script,g=e._deadScripts;if(g&&g.length>0){for(var f=0;f<
g.length;f++)e.remove(g[f].id,g[f].frameDoc),g[f].frameDoc=null;d.io.script._deadScripts=[]}return!0},_ioCheck:function(e){e=e.ioArgs;if(e.json||e.scriptLoaded&&!e.args.checkString)return!0;return(e=e.args.checkString)&&eval("typeof("+e+") != 'undefined'")},_resHandle:function(e){d.io.script._ioCheck(e)?e.callback(e):e.errback(Error("inconceivable dojo.io.script._resHandle error"))},_canAttach:function(){return!0},_jsonpCallback:function(e){this.ioArgs.json=e}};return d.io.script})},"dojo/_base/browser":function(){require.has&&
require.has.add("config-selectorEngine","acme");define("dojo/_base/browser",["../ready","./kernel","./connect","./unload","./window","./event","./html","./NodeList","../query","./xhr","./fx"],function(d){return d})},"djeo-ge/Placemark":function(){define("djeo-ge/Placemark",["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Color","djeo/_base","djeo/common/Placemark","djeo/util/_base","./_base"],function(d,j,h,e,g,f,m,l){var d=d([f],{constructor:function(a){j.mixin(this,a)},init:function(){this.ge=
this.map.engine.ge},render:function(a,b,c){google.earth.executeBatch(this.map.engine.ge,j.hitch(this,function(){this._render(a,b,c)}))},createPlacemark:function(){var a=this.ge.createPlacemark("");a.setStyleSelector(this.ge.createStyle(""));return a},makePoint:function(a,b){var c=this.createPlacemark(),i=this.ge.createPoint("");i.setLatLngAlt(b[1],b[0],o(a,b));this._setGeometryAttributes(a,i);c.setGeometry(i);return c},makeLineString:function(a,b){var c=this.createPlacemark(),i=this.ge.createLineString("");
this._makeLineString(a,i,b);this._setGeometryAttributes(a,i);c.setGeometry(i);return c},_makeLineString:function(a,b,c){h.forEach(c,function(c){b.getCoordinates().pushLatLngAlt(c[1],c[0],o(a,c))},this)},makePolygon:function(a,b){var c=this.createPlacemark(),i=this.ge.createPolygon("");this._makePolygon(a,i,b);this._setGeometryAttributes(a,i);c.setGeometry(i);return c},_makePolygon:function(a,b,c){h.forEach(c,function(c,e){var d=this.ge.createLinearRing("");h.forEach(c,function(b){d.getCoordinates().pushLatLngAlt(b[1],
b[0],o(a,b))});e?b.getInnerBoundaries().appendChild(d):b.setOuterBoundary(d)},this)},makeMultiLineString:function(a,b){var c=this.createPlacemark(),i=this.ge.createMultiGeometry("");this._setGeometryAttributes(a,i);c.setGeometry(i);h.forEach(b,function(b){var c=this.ge.createLineString("");this._makeLineString(a,c,b);i.getGeometries().appendChild(c)},this);return c},makeMultiPolygon:function(a,b){var c=this.createPlacemark(),i=this.ge.createMultiGeometry("");this._setGeometryAttributes(a,i);c.setGeometry(i);
h.forEach(b,function(b){var c=this.ge.createPolygon("");this._makePolygon(a,c,b);i.getGeometries().appendChild(c)},this);return c},_setGeometryAttributes:function(a,b){var c=g.getTraversedAttr(a,"altitudeMode");l.altitudeModes[c]&&b.setAltitudeMode(this.ge[l.altitudeModes[c]]);c=g.getTraversedAttr(a,"extrude");c!==void 0&&b.setExtrude(c);a.tessellate!=void 0&&b.setTessellate(a.tessellate)},applyPointStyle:function(a,b){var c=b.point,i=f.getSpecificShapeStyle(b.points,this.specificStyleIndex),e=a.baseShapes[0],
d=f.get("shape",b,c,i),g=f.getImgSrc(b,c,i),h=!0,o=f.getScale(b,c,i),p=e.getStyleSelector(),e=a.reg.kmlIconScale!==void 0?!0:!1;if(!d&&g)h=!1;else if(!f.shapes[d]&&!e)d=f.defaultShapeType;p=p.getIconStyle();if(d=h&&d?s+f.shapes[d]:this._getImageUrl(g))g=this.ge.createIcon(""),g.setHref(d),p.setIcon(g);var d=h?f.getSize(b,c,i):f.getImgSize(b,c,i),n;d?(n=h?o*Math.max(d[0],d[1])/l.shapeSize:o,a.reg.kmlIconScale=n):e&&(o=f.get("rScale",b,c,i),o!==void 0&&(n=o*a.reg.kmlIconScale));p.setScale(n);if(!e&&
(n=a.orientation,n!==void 0)){if(j.isObject(n))n=n.heading;p.setHeading(m.radToDeg(n))}h&&q(p,b,c,i,!0)},applyLineStyle:function(a,b){var c=b.line,d=f.getSpecificShapeStyle(b.lines,this.specificStyleIndex),e=a.baseShapes[0].getStyleSelector();p(e,b,c,d);a.extrude&&q(e,b,c,d)},applyPolygonStyle:function(a,b){var c=b.polygon,d=a.baseShapes[0].getStyleSelector();q(d,b,c);p(d,b,c)},remove:function(a){h.forEach(a.baseShapes,function(a){a.getParentNode().getFeatures().removeChild(a)})},show:function(a,
b){a.baseShapes[0].setVisibility(b)},makeText:function(a,b){if(a.getCoordsType()=="Point"){var c=f.get("text",b,b.point);if(c){var d=a.baseShapes[0],e=c.label||this._getLabel(a,c);if(e)d.setName(e),d=d.getStyleSelector().getLabelStyle(),c.fill&&d.getColor().set(n(c.fill,1)),c.geScale&&d.setScale(c.geScale),a.textShapes=!0}}},setCoords:function(a,b){var c=b.baseShapes[0].getGeometry();a.length==3?c.setLatLngAlt(a[1],a[0],a[2]):c.setLatLng(a[1],a[0])},setOrientation:function(a,b){b.baseShapes[0].getStyleSelector().getIconStyle().setHeading(m.radToDeg(a))}}),
s=function(a){for(var b=a.match(/\.\.\//g),c=b=b?b.length:0,d=m.baseUrl.length-1;b;)d--,m.baseUrl.charAt(d)=="/"&&b--;return m.baseUrl.substring(0,d)+"/"+a.substring(3*c)}(f.shapeIconsUrl),n=function(a,b){rgba=(new e(a)).toRgba();rgba[3]=Math.round(255*b);var c=h.map(rgba,function(a){a=a.toString(16);return a.length<2?"0"+a:a});return c[3]+c[2]+c[1]+c[0]},q=function(a,b,c,d,e){var g=f.get("fill",b,c,d),b=f.get("fillOpacity",b,c,d);if(g||b!==void 0)a=e?a:a.getPolyStyle(),a=a.getColor(),g=g?g:[a.getR(),
a.getG(),a.getB()],b=b!==void 0?b:a.getA()/255,a.set(n(g,b))},p=function(a,b,c,d){var e=f.get("stroke",b,c,d),g=f.get("strokeWidth",b,c,d),b=f.get("strokeOpacity",b,c,d);if(e||g!==void 0||b!==void 0)a=a.getLineStyle(),c=a.getColor(),e=e?e:[c.getR(),c.getG(),c.getB()],b=b!==void 0?b:c.getA()/255,c.set(n(e,b)),g!==void 0&&a.setWidth(g)},o=function(a,b){return b.length==3?b[2]:a.height?a.height:0};return d})},"djeo-ge/_base":function(){define("djeo-ge/_base",[],function(){return{shapeSize:50,altitudeModes:{clampToGround:"ALTITUDE_CLAMP_TO_GROUND",
relativeToGround:"ALTITUDE_RELATIVE_TO_GROUND",absolute:"ALTITUDE_ABSOLUTE"}}})},"dojo/DeferredList":function(){define("dojo/DeferredList",["./_base/kernel","./_base/Deferred","./_base/array"],function(d,j,h){d.DeferredList=function(d,g,f,m){var l=[];j.call(this);var s=this;d.length===0&&!g&&this.resolve([0,[]]);var n=0;h.forEach(d,function(h,j){function o(a,b){l[j]=[a,b];n++;n===d.length&&s.resolve(l)}h.then(function(a){g?s.resolve([j,a]):o(!0,a)},function(a){f?s.reject(a):o(!1,a);if(m)return null;
throw a;})})};d.DeferredList.prototype=new j;d.DeferredList.prototype.gatherResults=function(e){e=new d.DeferredList(e,!1,!0,!1);e.addCallback(function(d){var e=[];h.forEach(d,function(d){e.push(d[1])});return e});return e};return d.DeferredList})},"dojo/_base/NodeList":function(){define("dojo/_base/NodeList",["./kernel","../query","./array","./html","../NodeList-dom"],function(d,j,h){var j=j.NodeList,e=j.prototype;e.connect=j._adaptAsForEach(function(){return d.connect.apply(this,arguments)});e.coords=
j._adaptAsMap(d.coords);j.events=["blur","focus","change","click","error","keydown","keypress","keyup","load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","submit"];h.forEach(j.events,function(d){var f="on"+d;e[f]=function(d,e){return this.connect(f,d,e)}});d.NodeList=j;return d.NodeList})},"djeo-ge/Tooltip":function(){define("djeo-ge/Tooltip",["dojo/_base/declare"],function(d){return d(null,{init:function(){this.ge=this.map.engine.ge;this.balloon=this.ge.createHtmlStringBalloon("")},
pointeroverAction:function(d){var h=d.reg.cs,e=this.balloon,h=h.info?h.info(d):this.content(d);e.setContentString(h);e.setFeature(d.baseShapes[0]);this.ge.setBalloon(e)},pointeroutAction:function(){this.ge.setBalloon(null)}})})},"dojo/main":function(){define("dojo/main",["./_base/kernel","./has","require","./_base/sniff","./_base/lang","./_base/array","./ready","./_base/declare","./_base/connect","./_base/Deferred","./_base/json","./_base/Color","./has!dojo-firebug?./_firebug/firebug","./_base/browser",
"./_base/loader"],function(d,j,h,e,g,f,m){d.config.isDebug&&h(["./_firebug/firebug"]);var l=d.config.require;l&&(l=f.map(g.isArray(l)?l:[l],function(d){return d.replace(/\./g,"/")}),d.isAsync?h(l):m(1,function(){h(l)}));return d})},"djeo-ge/Engine":function(){define("djeo-ge/Engine",["require","dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/aspect","dojo/io/script","dojo/_base/Deferred","dojo/DeferredList","djeo/Engine","./Placemark","djeo/util/_base"],function(d,j,h,e,g,f,m,l,s,n,
q){var p={roadmap:1,hybrid:1,terrain:1};globeEvents={click:1,mousemove:1};var o=function(a,b){var c=q.degToRad(a[1]),d=q.degToRad(b[1]),e=q.degToRad(b[1]-a[1]),f=q.degToRad(b[0]-a[0]),c=Math.pow(Math.sin(e/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin(f/2),2);return q.earthRadius*2*Math.atan2(Math.sqrt(c),Math.sqrt(1-c))};return j([s],{type:"ge",canRenderModels:!0,ge:null,constructor:function(){this._require=d;h.mixin(this.ignoredDependencies,{Highlight:1});this._supportedLayers=p;this._initBasicFactories(new n({map:this.map}))},
initialize:function(a){window.google?google.load("earth","1",{callback:h.hitch(this,function(){google.earth.createInstance(this.map.container,h.hitch(this,function(b){this.map.projection="EPSG:4326";this.ge=b;this.ge.getOptions().setMouseNavigationEnabled(!1);this.ge.getWindow().setVisibility(!0);this.initialized=!0;a()}),function(){})})}):this._initializing?g.after(this,"_initializing",h.hitch(this,function(){this.initialize(a)})):(this._initializing=function(){},f.get({url:"https://www.google.com/jsapi",
load:h.hitch(this,function(){this._initializing();delete this._initializing;this.initialize(a)})}))},createContainer:function(a){var b=this.ge.createFolder("");this.appendChild(b,a);return b},prepare:function(){this.factories.Placemark.init()},appendChild:function(a,b){b.parent.getContainer().getFeatures().appendChild(a)},getTopContainer:function(){this.ge.getFeatures();return this.ge},onForFeature:function(a,b,c,d){var e=a.baseShapes[0],c=this.normalizeCallback(a,b,c,d);google.earth.addEventListener(e,
b,c);return[e,b,c]},onForMap:function(a,b,c){if(!(a in globeEvents))return{remove:function(){}};var d=this.ge.getGlobe(),e=function(a){b.call(c,{mapCoords:[a.getLongitude(),a.getLatitude()],nativeEvent:a})};google.earth.addEventListener(d,a,e);return{remove:function(){google.earth.removeEventListener(d,a,e)}}},disconnect:function(a){google.earth.removeEventListener(a[0],a[1],a[2])},zoomTo:function(a){var b=500,c=this.map.width/this.map.height,d=(a[0]+a[2])/2,e=(a[1]+a[3])/2,f=a[3]-a[1];if(a[2]-a[0]||
f)b=o([a[2],e],[a[0],e]),a=o([d,a[3]],[d,a[1]]),c=Math.min(Math.max(c,b/a),1),c=q.degToRad(45/(c+0.4)-2),a=Math.max(a,b),a=Math.min(q.degToRad(90),c+a/(2*q.earthRadius)),b=1.5*q.earthRadius*(Math.sin(a)*Math.sqrt(1+1/Math.pow(Math.tan(c),2))-1);c=this.ge.getView().copyAsLookAt(this.ge.ALTITUDE_RELATIVE_TO_GROUND);c.setLongitude(d);c.setLatitude(e);c.setAltitude(0);c.setRange(b);this.ge.getView().setAbstractView(c)},destroy:function(){},executeBatch:function(a){google.earth.executeBatch(this.ge,a)},
enableLayer:function(a,b){var c=this.ge,d=c.getLayerRoot();switch(a.toLowerCase()){case "roadmap":case "hybrid":d.enableLayerById(c.LAYER_BORDERS,b);d.enableLayerById(c.LAYER_ROADS,b);break;case "terrain":d.enableLayerById(c.LAYER_TERRAIN,b)}},renderFeatures:function(){var a=arguments;google.earth.executeBatch(this.ge,h.hitch(this,function(){this.inherited("renderFeatures",a)}))},renderContainer:function(a,b,c){var d=new m;google.earth.executeBatch(this.ge,h.hitch(this,function(){var e=this._renderContainer(a,
b,c);e&&e.length?(new l(e)).then(function(){d.resolve()}):d.resolve()}));return d},_renderContainer:function(a,b,c){if(a.visible){a.features.length==0&&c&&a.parent.numVisibleFeatures++;var d=[];e.forEach(a.features,function(a){if(a.isContainer||a.visible)(a=a._render(b,c))&&(h.isArray(a)?e.forEach(a,function(a){d.push(a)}):d.push(a))});return d.length?d:null}}})})}}});define("djeo-ge/ge",[],1);