//>>built
require({cache:{"djeo-leaflet/WebTiles":function(){define("djeo-leaflet/WebTiles",["dojo/_base/declare"],function(c){return c(null,{init:function(){this._tileLayer=tileLayer=new L.TileLayer("{s}/{z}/{"+(this.yFirst?"y}/{x":"x}/{y")+"}.png",{subdomains:this.url});this.map.engine.lmap.addLayer(tileLayer)}})})},"dojo/NodeList-dom":function(){define("dojo/NodeList-dom",["./_base/kernel","./query","./_base/array","./_base/lang","./dom-class","./dom-construct","./dom-geometry","./dom-attr","./dom-style"],
function(c,g,e,b,k,d,p,l,q){function h(a){return function(b,c,d){if(arguments.length==2)return a[typeof c=="string"?"get":"set"](b,c);return a.set(b,c,d)}}var a=function(a){return a.length==1&&typeof a[0]=="string"},f=function(a){var b=a.parentNode;b&&b.removeChild(a)},j=g.NodeList,n=j._adaptWithCondition,s=j._adaptAsForEach,o=j._adaptAsMap;b.extend(j,{_normalize:function(a,f){var q=a.parse===!0;if(typeof a.template=="string")var h=a.templateFunc||c.string&&c.string.substitute,a=h?h(a.template,a):
a;h=typeof a;h=="string"||h=="number"?(a=d.toDom(a,f&&f.ownerDocument),a=a.nodeType==11?b._toArray(a.childNodes):[a]):b.isArrayLike(a)?b.isArray(a)||(a=b._toArray(a)):a=[a];if(q)a._runParse=!0;return a},_cloneNode:function(a){return a.cloneNode(!0)},_place:function(a,b,f,q){if(!(b.nodeType!=1&&f=="only"))for(var h,j=a.length,l=j-1;l>=0;l--){var k=q?this._cloneNode(a[l]):a[l];if(a._runParse&&c.parser&&c.parser.parse){h||(h=b.ownerDocument.createElement("div"));h.appendChild(k);c.parser.parse(h);for(k=
h.firstChild;h.firstChild;)h.removeChild(h.firstChild)}l==j-1?d.place(k,b,f):b.parentNode.insertBefore(k,b);b=k}},attr:n(h(l),a),style:n(h(q),a),addClass:s(k.add),removeClass:s(k.remove),replaceClass:s(k.replace),toggleClass:s(k.toggle),empty:s(d.empty),removeAttr:s(l.remove),position:o(p.position),marginBox:o(p.getMarginBox),place:function(a,b){var c=g(a)[0];return this.forEach(function(a){d.place(a,c,b)})},orphan:function(a){return(a?g._filterResult(this,a):this).forEach(f)},adopt:function(a,b){return g(a).place(this[0],
b)._stash(this)},query:function(a){if(!a)return this;var b=new j;this.map(function(c){g(a,c).forEach(function(a){a!==void 0&&b.push(a)})});return b._stash(this)},filter:function(a){var b=arguments,c=this,d=0;if(typeof a=="string"){c=g._filterResult(this,b[0]);if(b.length==1)return c._stash(this);d=1}return this._wrap(e.filter(c,b[d],b[d+1]),this)},addContent:function(a,b){for(var a=this._normalize(a,this[0]),c=0,d;d=this[c];c++)this._place(a,d,b,c>0);return this}});return j})},"dojo/_base/loader":function(){define("dojo/_base/loader",
["./kernel","../has","require","module","./json","./lang","./array"],function(c,g,e,b,k,d,p){var l=function(a){return a.replace(/\./g,"/")},q=/\/\/>>built/,h=[],a=[],f,j=function(a){f[a.mid]=1;for(var b,c,d=a.deps||[],h=0;h<d.length;h++)if(c=d[h],!(b=f[c.mid]))if(b===0||!j(c))return f[a.mid]=0,!1;return!0},n=function(){var b,c;f={};for(c in z)if(b=z[c],b.executed||b.noReqPluginCheck)f[c]=1;else{if(b.noReqPluginCheck!==0)b.noReqPluginCheck=/loadInit\!/.test(c)||/require\!/.test(c)?1:0;b.noReqPluginCheck?
f[c]=1:b.injected!==x&&(f[c]=0)}for(var d=0,q=a.length;d<q;d++)if(b=a[d],!(c=f[b.mid]))if(c===0||!j(b))return;i.holdIdle();b=h;h=[];p.forEach(b,function(a){a(1)});i.releaseIdle()},s=function(a,b,d){var h=/\(|\)/g,f=1;for(h.lastIndex=b;b=h.exec(a);)if(b[0]==")"?f-=1:f+=1,f==0)break;if(f!=0)throw"unmatched paren around character "+h.lastIndex+" in: "+a;return[c.trim(a.substring(d,h.lastIndex))+";\n",h.lastIndex]},o=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,r=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,
m=/(^|\s)(require|define)\s*\(/m,v=function(a,b){var c,d,h,f=[],q=[];c=[];for(b=b||a.replace(o,function(a){r.lastIndex=m.lastIndex=0;return r.test(a)||m.test(a)?"":a});c=r.exec(b);)d=r.lastIndex,h=d-c[0].length,d=s(b,d,h),c[2]=="loadInit"?f.push(d[0]):q.push(d[0]),r.lastIndex=d[1];c=f.concat(q);return c.length||!m.test(b)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 && dojo.loadInit("),c.join(""),c]:0},i=e.initSyncLoader(function(b,c,d){h.push(d);p.forEach(b.split(","),function(b){b=t(b,c.module);
a.push(b);w(b)});n()},n,function(a,b){var d,h,f=[],l=[];if(q.test(b)||!(d=v(b)))return 0;h=a.mid+"-*loadInit";for(var j in t("dojo",a).result.scopeMap)f.push(j),l.push('"'+j+'"');return"// xdomain rewrite of "+a.path+"\ndefine('"+h+"',{\n\tnames:"+c.toJson(f)+",\n\tdef:function("+f.join(",")+"){"+d[1]+"}});\n\ndefine("+c.toJson(f.concat(["dojo/loadInit!"+h]))+", function("+f.join(",")+"){\n"+d[0]+"});"}),E=i.sync,x=i.arrived,y=i.nonmodule,F=i.executing,A=i.executed,u=i.syncExecStack,z=i.modules,B=
i.execQ,t=i.getModule,w=i.injectModule,C=i.setArrived,G=i.signal,H=i.finishExec,I=i.execModule,D=i.getLegacyMode;c.provide=function(a){var b=u[0],c=d.mixin(t(l(a),e.module),{executed:F,result:d.getObject(a,!0)});C(c);if(b)(b.provides||(b.provides=[])).push(function(){c.result=d.getObject(a);delete c.provides;c.executed!==A&&H(c)});return c.result};g.add("config-publishRequireResult",1,0,0);c.require=function(a,b){var c=function(a,b){var c=t(l(a),e.module);if(u.length&&u[0].finish)u[0].finish.push(a);
else{if(c.executed)return c.result;b&&(c.result=y);var d=D();w(c);d=D();c.executed!==A&&c.injected===x&&(i.holdIdle(),I(c),i.releaseIdle());if(c.executed)return c.result;d==E?c.cjs?B.unshift(c):u.length&&(u[0].finish=[a]):B.push(c)}}(a,b);g("config-publishRequireResult")&&!d.exists(a)&&c!==void 0&&d.setObject(a,c);return c};c.loadInit=function(a){a()};c.registerModulePath=function(a,b){var c={};c[a.replace(/\./g,"/")]=b;e({paths:c})};c.platformRequire=function(a){for(var a=(a.common||[]).concat(a[c._name]||
a["default"]||[]),b;a.length;)d.isArray(b=a.shift())?c.require.apply(c,b):c.require(b)};c.requireIf=c.requireAfterIf=function(a,b,d){a&&c.require(b,d)};c.requireLocalization=function(a,b,c){e(["../i18n"],function(d){d.getLocalization(a,b,c)})};return{extractLegacyApiApplications:v,require:i.dojoRequirePlugin,loadInit:function(d,f,q){f([d],function(d){f(d.names,function(){for(var j="",k=[],e=0;e<arguments.length;e++)j+="var "+d.names[e]+"= arguments["+e+"]; ",k.push(arguments[e]);eval(j);var g=f.module,
i=[],j={},o=[],m,e={provide:function(a){a=l(a);a=t(a,g);a!==g&&C(a)},require:function(a,b){a=l(a);b&&(t(a,g).result=y);o.push(a)},requireLocalization:function(a,b,d){i.length||(i=["dojo/i18n"]);d=(d||c.locale).toLowerCase();a=l(a)+"/nls/"+(/root/i.test(d)?"":d+"/")+l(b);t(a,g).isXd&&i.push("dojo/i18n!"+a)},loadInit:function(a){a()}};try{for(m in e)j[m]=c[m],c[m]=e[m];d.def.apply(null,k)}catch(s){G("error",[{src:b.id,id:"failedDojoLoadInit"},s])}finally{for(m in e)c[m]=j[m]}o.length&&i.push("dojo/require!"+
o.join(","));h.push(q);p.forEach(o,function(b){b=t(b,f.module);a.push(b);w(b)});n()})})}}})},"dojo/io/script":function(){define("dojo/io/script",["../main"],function(c){c.getObject("io",!0,c);var g=c.isIE?"onreadystatechange":"load",e=/complete|loaded/;c.io.script={get:function(b){var k=this._makeScriptDeferred(b),d=k.ioArgs;c._ioAddQueryToUrl(d);c._ioNotifyStart(k);if(this._canAttach(d)){var p=this.attach(d.id,d.url,b.frameDoc);if(!d.jsonp&&!d.args.checkString)var l=c.connect(p,g,function(b){if(b.type==
"load"||e.test(p.readyState))c.disconnect(l),d.scriptLoaded=b})}c._ioWatch(k,this._validCheck,this._ioCheck,this._resHandle);return k},attach:function(b,k,d){var d=d||c.doc,e=d.createElement("script");e.type="text/javascript";e.src=k;e.id=b;e.async=!0;e.charset="utf-8";return d.getElementsByTagName("head")[0].appendChild(e)},remove:function(b,e){c.destroy(c.byId(b,e));this["jsonp_"+b]&&delete this["jsonp_"+b]},_makeScriptDeferred:function(b){var e=c._ioSetArgs(b,this._deferredCancel,this._deferredOk,
this._deferredError),d=e.ioArgs;d.id=c._scopeName+"IoScript"+this._counter++;d.canDelete=!1;d.jsonp=b.callbackParamName||b.jsonp;if(d.jsonp)d.query=d.query||"",d.query.length>0&&(d.query+="&"),d.query+=d.jsonp+"="+(b.frameDoc?"parent.":"")+c._scopeName+".io.script.jsonp_"+d.id+"._jsonpCallback",d.frameDoc=b.frameDoc,d.canDelete=!0,e._jsonpCallback=this._jsonpCallback,this["jsonp_"+d.id]=e;return e},_deferredCancel:function(b){b.canceled=!0;b.ioArgs.canDelete&&c.io.script._addDeadScript(b.ioArgs)},
_deferredOk:function(b){b=b.ioArgs;b.canDelete&&c.io.script._addDeadScript(b);return b.json||b.scriptLoaded||b},_deferredError:function(b,e){e.ioArgs.canDelete&&(b.dojoType=="timeout"?c.io.script.remove(e.ioArgs.id,e.ioArgs.frameDoc):c.io.script._addDeadScript(e.ioArgs));return b},_deadScripts:[],_counter:1,_addDeadScript:function(b){c.io.script._deadScripts.push({id:b.id,frameDoc:b.frameDoc});b.frameDoc=null},_validCheck:function(){var b=c.io.script,e=b._deadScripts;if(e&&e.length>0){for(var d=0;d<
e.length;d++)b.remove(e[d].id,e[d].frameDoc),e[d].frameDoc=null;c.io.script._deadScripts=[]}return!0},_ioCheck:function(b){b=b.ioArgs;if(b.json||b.scriptLoaded&&!b.args.checkString)return!0;return(b=b.args.checkString)&&eval("typeof("+b+") != 'undefined'")},_resHandle:function(b){c.io.script._ioCheck(b)?b.callback(b):b.errback(Error("inconceivable dojo.io.script._resHandle error"))},_canAttach:function(){return!0},_jsonpCallback:function(b){this.ioArgs.json=b}};return c.io.script})},"dojo/_base/browser":function(){require.has&&
require.has.add("config-selectorEngine","acme");define("dojo/_base/browser",["../ready","./kernel","./connect","./unload","./window","./event","./html","./NodeList","../query","./xhr","./fx"],function(c){return c})},"djeo-leaflet/Navigation":function(){define("djeo-leaflet/Navigation",["dojo/_base/declare"],function(c){return c(null,{enable:function(c){c===void 0&&(c=!0);var e=this.map.engine.lmap;c?(e.dragging.enable(),e.touchZoom.enable(),e.scrollWheelZoom.enable(),e.doubleClickZoom.enable(),e.on("zoomend",
this._onZoom,this)):(e.dragging.disable(),e.touchZoom.disable(),e.scrollWheelZoom.disable(),e.doubleClickZoom.disable(),e.off("zoomend",this._onZoom,this))}})})},"djeo-leaflet/Engine":function(){define("djeo-leaflet/Engine",["require","dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/aspect","dojo/io/script","djeo/Engine","./Placemark","djeo/_tiles","xstyle/css!./dist/leaflet.css"],function(c,g,e,b,k,d,p,l,q){function h(a,b,c,d){return{remove:function(){a.off(b,c,d)}}}return g([p],{lmap:null,
constructor:function(){this._require=c;e.mixin(this.ignoredDependencies,{Highlight:1,Tooltip:1});this._supportedLayers=q;this._initBasicFactories(new l({map:this.map,engine:this}))},initialize:function(a){if(window.L){var b=this.map;b.projection="EPSG:4326";this.lmap=new L.Map(b.container,{minZoom:b.minZoom,maxZoom:b.maxZoom,touchZoom:!1,scrollWheelZoom:!1,doubleClickZoom:!1,zoomControl:!1,attributionControl:!1});this.initialized=!0;a()}else this._initializing?k.after(this,"_initializing",e.hitch(this,
function(){this.initialize(a)})):(this._initializing=function(){},d.get({url:c.toUrl("./dist/leaflet.js"),load:e.hitch(this,function(){this._initializing();delete this._initializing;this.initialize(a)})}))},createContainer:function(){},appendChild:function(a){this.lmap.addLayer(a)},getTopContainer:function(){this.ge.getFeatures();return this.ge},onForFeature:function(a,c,d,h){var e=[],d=this.normalizeCallback(a,c,d,h);b.forEach(a.baseShapes,function(a){e.push([a,c,d]);a.on(c,d)});return e},disconnect:function(a){b.forEach(a,
function(a){a[0].off(a[1],a[2])})},onForMap:function(a,b,c){var d=function(a){var d=a.latlng;b.call(c,{mapCoords:[d.lng,d.lat],nativeEvent:a})};this.lmap.on(a,d);return h(this.lmap,a,d)},_on_zoom_changed:function(a,b,c){this.lmap.on("zoomend",b,c);return h(this.lmap,"zoomend",b,c)},_on_extent_changed:function(a,b,c){this.lmap.on("moveend",b,c);return h(this.lmap,"moveend",b,c)},zoomTo:function(a){a[0]==a[2]&&a[1]==a[3]&&(a=[0.99999*a[0],0.99999*a[1],1.00001*a[2],1.00001*a[3]]);this.lmap.fitBounds(new L.LatLngBounds(new L.LatLng(a[1],
a[0]),new L.LatLng(a[3],a[2])))},destroy:function(){},_setCamera:function(a){var b=a.center,b=new L.LatLng(b[1],b[0]);this.lmap.setView(b,a.zoom)},_set_center:function(a){this.lmap.setView(new L.LatLng(a[1],a[0]),this.lmap.getZoom())},_get_center:function(){var a=this.lmap.getCenter();return[a.lng,a.lat]},_set_zoom:function(a){this.lmap.setZoom(a)},_get_zoom:function(){return this.lmap.getZoom()},_get_extent:function(){var a=this.lmap.getBounds(),b=a.getSouthWest(),a=a.getNorthEast();return[b.lng,
b.lat,a.lng,a.lat]}})})},"djeo/WebTiles":function(){define("djeo/WebTiles",["dojo/_base/declare","dojo/_base/lang","./_base"],function(c,g,e){e.registerDependency("WebTiles");return c(null,{yFirst:!1,dependency:"WebTiles",constructor:function(b){g.mixin(this,b);b=b.paramStr?b.paramStr:this.url;if(g.isString(b)){var c=b.indexOf("[");if(c>-1){var d=b.indexOf("]");parts=b.substring(c+1,d).split(",");this.url=[];for(var e=0;e<parts.length;e++)this.url[e]=b.substring(0,c)+parts[e]+b.substring(d+1)}else this.url=
[b]}this.numUrls=this.url.length},startup:function(b){this.map=b;if(b=this.map.engine.getFactory("WebTiles"))g.mixin(this,b),this.init()}})})},"dojo/_base/NodeList":function(){define("dojo/_base/NodeList",["./kernel","../query","./array","./html","../NodeList-dom"],function(c,g,e){var g=g.NodeList,b=g.prototype;b.connect=g._adaptAsForEach(function(){return c.connect.apply(this,arguments)});b.coords=g._adaptAsMap(c.coords);g.events=["blur","focus","change","click","error","keydown","keypress","keyup",
"load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","submit"];e.forEach(g.events,function(c){var d="on"+c;b[d]=function(b,c){return this.connect(d,b,c)}});c.NodeList=g;return c.NodeList})},"djeo/_tiles":function(){define("djeo/_tiles",[],function(){var c=["WebTiles",{url:"http://[a,b,c].tile.openstreetmap.org"}];return{webtiles:["WebTiles",{}],roadmap:c,osm:c,openstreetmap:c,"osm.org":c,"openstreetmap.org":c,"mapquest-osm":["WebTiles",{url:"http://otile[1,2,3,4].mqcdn.com/tiles/1.0.0/osm"}],
"mapquest-oa":["WebTiles",{url:"http://oatile[1,2,3,4].mqcdn.com/tiles/1.0.0/sat"}],arcgis_webtiles:["WebTiles",{}]}})},"djeo-leaflet/Placemark":function(){define("djeo-leaflet/Placemark",["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Color","djeo/util/_base","djeo/common/Placemark"],function(c,g,e,b,k,d){function p(b,c){var d=c.match(/\b\w+\.\w{3,4}$/)[0].split("."),c=[c.substr(0,c.length-d[0].length-d[1].length-1)+d[0]+"_"+d[1]+"/",d[0],d[1]];return b.reg.url=c}return c([d],
{constructor:function(b){g.mixin(this,b)},makePoint:function(){},makeLineString:function(b,c){var d=[];e.forEach(c,function(a){d.push(new L.LatLng(a[1],a[0]))});return new L.Polyline(d)},makePolygon:function(b,c){var d=[];e.forEach(c,function(a){var b=[];e.forEach(a,function(a){b.push(new L.LatLng(a[1],a[0]))});d.push(b)});return new L.Polygon(d)},makeMultiLineString:function(b,c){var d=[];e.forEach(c,function(a){var b=[];e.forEach(a,function(a){b.push(new L.LatLng(a[1],a[0]))});d.push(b)},this);
return new L.MultiPolyline(d)},makeMultiPolygon:function(b,c){var d=[];e.forEach(c,function(a){e.forEach(a,function(a){var b=[];e.forEach(a,function(a){b.push(new L.LatLng(a[1],a[0]))});d.push(b)})},this);return new L.MultiPolygon(d)},applyPointStyle:function(b,c,e){var a=c.point,f=d.getSpecificShapeStyle(c.points,this.specificStyleIndex),j=b.baseShapes[0],n=d.get("shape",c,a,f),s=d.getImgSrc(c,a,f),o=!0,r=d.getScale(c,a,f),m=b.orientation,v=b.map.simulateOrientation&&m!==void 0;if(!n&&s)o=!1;else if(!d.shapes[n]&&
!j)n=d.defaultShapeType;var i=j?j.options.icon.options:{shadowUrl:""},n=this._getIconUrl(o,n,s);if(v){if(g.isObject(m))m=m.heading;m=Math.round(k.radToDeg(m));m<0&&(m=360+m);n&&(n=p(b,n),n=n[0]+n[1]+"_"+m+"."+n[2])}if(n)i.iconUrl=n;if(m=o?d.getSize(c,a,f):d.getImgSize(c,a,f))c=o?[m[0]/2,m[1]/2]:d.getAnchor(c,a,f,m),i.iconSize=[r*m[0],r*m[1]],i.iconAnchor=[r*c[0],r*c[1]];else if(j&&(r=d.get("rScale",c,a,f),r!==void 0))c=i.iconSize,a=i.iconAnchor,i.iconSize=[r*c[0],r*c[1]],i.iconAnchor=[r*a[0],r*a[1]];
i=new L.Icon(i);j?j.setIcon(i):b.baseShapes[0]=new L.Marker([e[1],e[0]],{icon:i})},applyLineStyle:function(b,c){var e=c.line,a=d.getSpecificShapeStyle(c.lines,this.specificStyleIndex),f=b.baseShapes[0],j=d.get("stroke",c,e,a),g=d.get("strokeOpacity",c,e,a),e=d.get("strokeWidth",c,e,a),a={};if(j)a.color=j;if(g!==void 0)a.opacity=g;if(e!==void 0)a.weight=e;f.setStyle(a)},applyPolygonStyle:function(b,c){var e=c.polygon,a=b.baseShapes[0],f=d.get("fill",c,e),j=d.get("fillOpacity",c,e),g=d.get("stroke",
c,e),k=d.get("strokeOpacity",c,e),e=d.get("strokeWidth",c,e),o={};if(f)o.fillColor=f;if(j!==void 0)o.fillOpacity=j;if(g)o.color=g;if(k!==void 0)o.opacity=k;if(e!==void 0)o.weight=e;a.setStyle(o)},remove:function(){},show:function(b,c){c?this.engine.lmap.addLayer(b.baseShapes[0]):this.engine.lmap.removeLayer(b.baseShapes[0])},makeText:function(){},setCoords:function(b,c){var d=new L.LatLng(b[1],b[0]);c.baseShapes[0].setLatLng(d)},setOrientation:function(b,c){if(c.map.simulateOrientation){var d=c.baseShapes[0],
a=d.options.icon.options,e=Math.round(k.radToDeg(b)),g=c.reg.url;g||(g=p(c,a.iconUrl));e<0&&(e=360+e);a.iconUrl=g[0]+g[1]+"_"+e+"."+g[2];d.setIcon(new L.Icon(a))}}})})},"dojo/main":function(){define("dojo/main",["./_base/kernel","./has","require","./_base/sniff","./_base/lang","./_base/array","./ready","./_base/declare","./_base/connect","./_base/Deferred","./_base/json","./_base/Color","./has!dojo-firebug?./_firebug/firebug","./_base/browser","./_base/loader"],function(c,g,e,b,k,d,p){c.config.isDebug&&
e(["./_firebug/firebug"]);var l=c.config.require;l&&(l=d.map(k.isArray(l)?l:[l],function(b){return b.replace(/\./g,"/")}),c.isAsync?e(l):p(1,function(){e(l)}));return c})}}});define("djeo-leaflet/leaflet",[],1);