//>>built
require({cache:{"dojo/NodeList-dom":function(){define("dojo/NodeList-dom",["./_base/kernel","./query","./_base/array","./_base/lang","./dom-class","./dom-construct","./dom-geometry","./dom-attr","./dom-style"],function(c,j,d,b,k,e,i,o,s){function p(a){return function(c,b,f){if(arguments.length==2)return a[typeof b=="string"?"get":"set"](c,b);return a.set(c,b,f)}}var h=function(a){return a.length==1&&typeof a[0]=="string"},f=function(a){var c=a.parentNode;c&&c.removeChild(a)},a=j.NodeList,n=a._adaptWithCondition,
q=a._adaptAsForEach,l=a._adaptAsMap;b.extend(a,{_normalize:function(a,f){var n=a.parse===!0;if(typeof a.template=="string")var g=a.templateFunc||c.string&&c.string.substitute,a=g?g(a.template,a):a;g=typeof a;g=="string"||g=="number"?(a=e.toDom(a,f&&f.ownerDocument),a=a.nodeType==11?b._toArray(a.childNodes):[a]):b.isArrayLike(a)?b.isArray(a)||(a=b._toArray(a)):a=[a];if(n)a._runParse=!0;return a},_cloneNode:function(a){return a.cloneNode(!0)},_place:function(a,b,f,n){if(!(b.nodeType!=1&&f=="only"))for(var h,
i=a.length,k=i-1;k>=0;k--){var d=n?this._cloneNode(a[k]):a[k];if(a._runParse&&c.parser&&c.parser.parse){h||(h=b.ownerDocument.createElement("div"));h.appendChild(d);c.parser.parse(h);for(d=h.firstChild;h.firstChild;)h.removeChild(h.firstChild)}k==i-1?e.place(d,b,f):b.parentNode.insertBefore(d,b);b=d}},attr:n(p(o),h),style:n(p(s),h),addClass:q(k.add),removeClass:q(k.remove),replaceClass:q(k.replace),toggleClass:q(k.toggle),empty:q(e.empty),removeAttr:q(o.remove),position:l(i.position),marginBox:l(i.getMarginBox),
place:function(a,c){var b=j(a)[0];return this.forEach(function(a){e.place(a,b,c)})},orphan:function(a){return(a?j._filterResult(this,a):this).forEach(f)},adopt:function(a,c){return j(a).place(this[0],c)._stash(this)},query:function(c){if(!c)return this;var b=new a;this.map(function(a){j(c,a).forEach(function(a){a!==void 0&&b.push(a)})});return b._stash(this)},filter:function(a){var c=arguments,b=this,f=0;if(typeof a=="string"){b=j._filterResult(this,c[0]);if(c.length==1)return b._stash(this);f=1}return this._wrap(d.filter(b,
c[f],c[f+1]),this)},addContent:function(a,c){for(var a=this._normalize(a,this[0]),b=0,f;f=this[b];b++)this._place(a,f,c,b>0);return this}});return a})},"dojo/_base/loader":function(){define("dojo/_base/loader",["./kernel","../has","require","module","./json","./lang","./array"],function(c,j,d,b,k,e,i){var o=function(a){return a.replace(/\./g,"/")},s=/\/\/>>built/,p=[],h=[],f,a=function(c){f[c.mid]=1;for(var b,h,n=c.deps||[],e=0;e<n.length;e++)if(h=n[e],!(b=f[h.mid]))if(b===0||!a(h))return f[c.mid]=
0,!1;return!0},n=function(){var c,b;f={};for(b in A)if(c=A[b],c.executed||c.noReqPluginCheck)f[b]=1;else{if(c.noReqPluginCheck!==0)c.noReqPluginCheck=/loadInit\!/.test(b)||/require\!/.test(b)?1:0;c.noReqPluginCheck?f[b]=1:c.injected!==r&&(f[b]=0)}for(var n=0,e=h.length;n<e;n++)if(c=h[n],!(b=f[c.mid]))if(b===0||!a(c))return;g.holdIdle();c=p;p=[];i.forEach(c,function(a){a(1)});g.releaseIdle()},q=function(a,b,f){var n=/\(|\)/g,h=1;for(n.lastIndex=b;b=n.exec(a);)if(b[0]==")"?h-=1:h+=1,h==0)break;if(h!=
0)throw"unmatched paren around character "+n.lastIndex+" in: "+a;return[c.trim(a.substring(f,n.lastIndex))+";\n",n.lastIndex]},l=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,v=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,t=/(^|\s)(require|define)\s*\(/m,m=function(a,c){var b,f,n,h=[],e=[];b=[];for(c=c||a.replace(l,function(a){v.lastIndex=t.lastIndex=0;return v.test(a)||t.test(a)?"":a});b=v.exec(c);)f=v.lastIndex,n=f-b[0].length,f=q(c,f,n),b[2]==
"loadInit"?h.push(f[0]):e.push(f[0]),v.lastIndex=f[1];b=h.concat(e);return b.length||!t.test(c)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 && dojo.loadInit("),b.join(""),b]:0},g=d.initSyncLoader(function(a,b,c){p.push(c);i.forEach(a.split(","),function(a){a=u(a,b.module);h.push(a);z(a)});n()},n,function(a,b){var f,n,h=[],e=[];if(s.test(b)||!(f=m(b)))return 0;n=a.mid+"-*loadInit";for(var g in u("dojo",a).result.scopeMap)h.push(g),e.push('"'+g+'"');return"// xdomain rewrite of "+a.path+"\ndefine('"+
n+"',{\n\tnames:"+c.toJson(h)+",\n\tdef:function("+h.join(",")+"){"+f[1]+"}});\n\ndefine("+c.toJson(h.concat(["dojo/loadInit!"+n]))+", function("+h.join(",")+"){\n"+f[0]+"});"}),y=g.sync,r=g.arrived,w=g.nonmodule,F=g.executing,B=g.executed,x=g.syncExecStack,A=g.modules,C=g.execQ,u=g.getModule,z=g.injectModule,D=g.setArrived,G=g.signal,H=g.finishExec,I=g.execModule,E=g.getLegacyMode;c.provide=function(a){var b=x[0],c=e.mixin(u(o(a),d.module),{executed:F,result:e.getObject(a,!0)});D(c);if(b)(b.provides||
(b.provides=[])).push(function(){c.result=e.getObject(a);delete c.provides;c.executed!==B&&H(c)});return c.result};j.add("config-publishRequireResult",1,0,0);c.require=function(a,b){var c=function(a,c){var b=u(o(a),d.module);if(x.length&&x[0].finish)x[0].finish.push(a);else{if(b.executed)return b.result;c&&(b.result=w);var f=E();z(b);f=E();b.executed!==B&&b.injected===r&&(g.holdIdle(),I(b),g.releaseIdle());if(b.executed)return b.result;f==y?b.cjs?C.unshift(b):x.length&&(x[0].finish=[a]):C.push(b)}}(a,
b);j("config-publishRequireResult")&&!e.exists(a)&&c!==void 0&&e.setObject(a,c);return c};c.loadInit=function(a){a()};c.registerModulePath=function(a,b){var c={};c[a.replace(/\./g,"/")]=b;d({paths:c})};c.platformRequire=function(a){for(var a=(a.common||[]).concat(a[c._name]||a["default"]||[]),b;a.length;)e.isArray(b=a.shift())?c.require.apply(c,b):c.require(b)};c.requireIf=c.requireAfterIf=function(a,b,f){a&&c.require(b,f)};c.requireLocalization=function(a,b,c){d(["../i18n"],function(f){f.getLocalization(a,
b,c)})};return{extractLegacyApiApplications:m,require:g.dojoRequirePlugin,loadInit:function(a,f,e){f([a],function(a){f(a.names,function(){for(var g="",k=[],d=0;d<arguments.length;d++)g+="var "+a.names[d]+"= arguments["+d+"]; ",k.push(arguments[d]);eval(g);var l=f.module,q=[],g={},j=[],m,d={provide:function(a){a=o(a);a=u(a,l);a!==l&&D(a)},require:function(a,b){a=o(a);b&&(u(a,l).result=w);j.push(a)},requireLocalization:function(a,b,f){q.length||(q=["dojo/i18n"]);f=(f||c.locale).toLowerCase();a=o(a)+
"/nls/"+(/root/i.test(f)?"":f+"/")+o(b);u(a,l).isXd&&q.push("dojo/i18n!"+a)},loadInit:function(a){a()}};try{for(m in d)g[m]=c[m],c[m]=d[m];a.def.apply(null,k)}catch(v){G("error",[{src:b.id,id:"failedDojoLoadInit"},v])}finally{for(m in d)c[m]=g[m]}j.length&&q.push("dojo/require!"+j.join(","));p.push(e);i.forEach(j,function(a){a=u(a,f.module);h.push(a);z(a)});n()})})}}})},"dojo/io/script":function(){define("dojo/io/script",["../main"],function(c){c.getObject("io",!0,c);var j=c.isIE?"onreadystatechange":
"load",d=/complete|loaded/;c.io.script={get:function(b){var k=this._makeScriptDeferred(b),e=k.ioArgs;c._ioAddQueryToUrl(e);c._ioNotifyStart(k);if(this._canAttach(e)){var i=this.attach(e.id,e.url,b.frameDoc);if(!e.jsonp&&!e.args.checkString)var o=c.connect(i,j,function(b){if(b.type=="load"||d.test(i.readyState))c.disconnect(o),e.scriptLoaded=b})}c._ioWatch(k,this._validCheck,this._ioCheck,this._resHandle);return k},attach:function(b,d,e){var e=e||c.doc,i=e.createElement("script");i.type="text/javascript";
i.src=d;i.id=b;i.async=!0;i.charset="utf-8";return e.getElementsByTagName("head")[0].appendChild(i)},remove:function(b,d){c.destroy(c.byId(b,d));this["jsonp_"+b]&&delete this["jsonp_"+b]},_makeScriptDeferred:function(b){var d=c._ioSetArgs(b,this._deferredCancel,this._deferredOk,this._deferredError),e=d.ioArgs;e.id=c._scopeName+"IoScript"+this._counter++;e.canDelete=!1;e.jsonp=b.callbackParamName||b.jsonp;if(e.jsonp)e.query=e.query||"",e.query.length>0&&(e.query+="&"),e.query+=e.jsonp+"="+(b.frameDoc?
"parent.":"")+c._scopeName+".io.script.jsonp_"+e.id+"._jsonpCallback",e.frameDoc=b.frameDoc,e.canDelete=!0,d._jsonpCallback=this._jsonpCallback,this["jsonp_"+e.id]=d;return d},_deferredCancel:function(b){b.canceled=!0;b.ioArgs.canDelete&&c.io.script._addDeadScript(b.ioArgs)},_deferredOk:function(b){b=b.ioArgs;b.canDelete&&c.io.script._addDeadScript(b);return b.json||b.scriptLoaded||b},_deferredError:function(b,d){d.ioArgs.canDelete&&(b.dojoType=="timeout"?c.io.script.remove(d.ioArgs.id,d.ioArgs.frameDoc):
c.io.script._addDeadScript(d.ioArgs));return b},_deadScripts:[],_counter:1,_addDeadScript:function(b){c.io.script._deadScripts.push({id:b.id,frameDoc:b.frameDoc});b.frameDoc=null},_validCheck:function(){var b=c.io.script,d=b._deadScripts;if(d&&d.length>0){for(var e=0;e<d.length;e++)b.remove(d[e].id,d[e].frameDoc),d[e].frameDoc=null;c.io.script._deadScripts=[]}return!0},_ioCheck:function(b){b=b.ioArgs;if(b.json||b.scriptLoaded&&!b.args.checkString)return!0;return(b=b.args.checkString)&&eval("typeof("+
b+") != 'undefined'")},_resHandle:function(b){c.io.script._ioCheck(b)?b.callback(b):b.errback(Error("inconceivable dojo.io.script._resHandle error"))},_canAttach:function(){return!0},_jsonpCallback:function(b){this.ioArgs.json=b}};return c.io.script})},"dojo/_base/browser":function(){require.has&&require.has.add("config-selectorEngine","acme");define("dojo/_base/browser",["../ready","./kernel","./connect","./unload","./window","./event","./html","./NodeList","../query","./xhr","./fx"],function(c){return c})},
"djeo-gmaps/Navigation":function(){define("djeo-gmaps/Navigation",["dojo/_base/declare","dojo/_base/lang"],function(c,j){return c(null,{enable:function(c){c===void 0&&(c=!0);var b=this.map.engine.gmap;b.setOptions({disableDoubleClickZoom:!c,draggable:c,scrollwheel:c});c?this.zoomListener=google.maps.event.addListener(b,"zoom_changed",j.hitch(this,this._onZoom)):(google.maps.event.removeListener(this.zoomListener),delete this.zoomListener)}})})},"djeo-gmaps/Engine":function(){define("djeo-gmaps/Engine",
["require","dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/aspect","dojo/io/script","djeo/Engine","./Placemark","djeo/_tiles"],function(c,j,d,b,k,e,i,o,s){function p(a){return{remove:function(){h.event.removeListener(a)}}}var h=window.google&&google.maps,f={roadmap:"ROADMAP",satellite:"SATELLITE",hybrid:"HYBRID",terrain:"TERRAIN"},s=d.mixin(d.mixin({},s),f);return j([i],{gmap:null,constructor:function(){this._require=c;d.mixin(this.ignoredDependencies,{Highlight:1,Tooltip:1});this._supportedLayers=
s;this._initBasicFactories(o({map:this.map}))},initialize:function(a){if(h){var b=this.map;b.projection="EPSG:4326";this.gmap=new h.Map(b.container,{zoom:0,minZoom:b.minZoom,maxZoom:b.maxZoom,center:new h.LatLng(0,0),disableDefaultUI:!0,disableDoubleClickZoom:!0,draggable:!1,scrollwheel:!1});this.initialized=!0;a()}else window._djeoGmapsInitialized?k.after(window,"_djeoGmapsInitialized",d.hitch(this,function(){this.initialize(a)})):(window._djeoGmapsInitialized=d.hitch(this,function(){window._djeoGmapsInitialized=
null;o.init();h=google.maps;this.initialize(a)}),e.get({url:"http://maps.google.com/maps/api/js",content:{sensor:!1,callback:"_djeoGmapsInitialized"}}))},_initialize:function(){},createContainer:function(a){var b=this.ge.createFolder("");this.appendChild(b,a);return b},appendChild:function(a,b){a.setMap(b.map.engine.gmap)},getTopContainer:function(){this.ge.getFeatures();return this.ge},onForFeature:function(a,c,f,d){var e=[],f=this.normalizeCallback(a,c,f,d);b.forEach(a.baseShapes,function(a){e.push(h.event.addListener(a,
c,f))});return e},disconnect:function(a){b.forEach(a,function(a){h.event.removeListener(a)})},onForMap:function(a,b,c){return p(h.event.addListener(this.gmap,a,function(a){var f=a.latLng;b.call(c,{mapCoords:[f.lng(),f.lat()],nativeEvent:a})}))},_on_zoom_changed:function(a,b,c){return p(h.event.addListener(this.gmap,"zoom_changed",function(){b.call(c)}))},_on_extent_changed:function(a,b,c){return p(h.event.addListener(this.gmap,"bounds_changed",function(){b.call(c)}))},zoomTo:function(a){this.gmap.fitBounds(new h.LatLngBounds(new h.LatLng(a[1],
a[0]),new h.LatLng(a[3],a[2])))},destroy:function(){},enableLayer:function(a,b){if(d.isString(a)){var c=a.toLowerCase();c in f?b&&this.gmap.setMapTypeId(h.MapTypeId[f[c]]):this.inherited(arguments)}else this.inherited(arguments)},getLayerModuleId:function(a){if(a.toLowerCase()in f)return null;return this.inherited(arguments)},_setCamera:function(a){this._set_center(a.center);this._set_zoom(a.zoom)},_set_center:function(a){this.gmap.setCenter(new h.LatLng(a[1],a[0]))},_get_center:function(){var a=
this.gmap.getCenter();return[a.lng(),a.lat()]},_set_zoom:function(a){this.gmap.setZoom(a)},_get_zoom:function(){return this.gmap.getZoom()},_get_extent:function(){var a=this.gmap.getBounds(),b=a.getSouthWest(),a=a.getNorthEast();return[b.lng(),b.lat(),a.lng(),a.lat()]}})})},"dojo/_base/NodeList":function(){define("dojo/_base/NodeList",["./kernel","../query","./array","./html","../NodeList-dom"],function(c,j,d){var j=j.NodeList,b=j.prototype;b.connect=j._adaptAsForEach(function(){return c.connect.apply(this,
arguments)});b.coords=j._adaptAsMap(c.coords);j.events=["blur","focus","change","click","error","keydown","keypress","keyup","load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","submit"];d.forEach(j.events,function(c){var e="on"+c;b[e]=function(b,c){return this.connect(e,b,c)}});c.NodeList=j;return c.NodeList})},"djeo-gmaps/Placemark":function(){define("djeo-gmaps/Placemark",["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Color","dojo/has",
"djeo/util/_base","djeo/common/Placemark","dojo/_base/sniff"],function(c,j,d,b,k,e,i){function o(c){return k("ie")?(new b(c)).toHex():c}function s(b,c){var a=c.match(/\b\w+\.\w{3,4}$/)[0],e=a.split("."),c=c.substr(0,c.length-e[0].length-e[1].length-1)+e[0]+"_"+e[1]+"/"+a;return b.reg.url=c}var p=window.google&&google.maps,c=c([i],{constructor:function(b){j.mixin(this,b)},makePoint:function(b,c){return new p.Marker({position:new p.LatLng(c[1],c[0])})},makeLineString:function(b,c){return this._makeLineString(c)},
_makeLineString:function(b){var c=[];d.forEach(b,function(a){c.push(new p.LatLng(a[1],a[0]))});return new p.Polyline({path:c})},makePolygon:function(b,c){return new p.Polygon({paths:this._makePolygonPaths(c,[])})},_makePolygonPaths:function(b,c){d.forEach(b,function(a){var b=[];d.forEach(a,function(a){b.push(new p.LatLng(a[1],a[0]))});c.push(b)});return c},makeMultiLineString:function(b,c){d.forEach(c,function(a){b.baseShapes.push(this._makeLineString(a))},this);return null},makeMultiPolygon:function(b,
c){var a=[];d.forEach(c,function(b){this._makePolygonPaths(b,a)},this);return new p.Polygon({paths:a})},applyPointStyle:function(b,c){var a=c.point,d=i.getSpecificShapeStyle(c.points,this.specificStyleIndex),o=b.baseShapes[0],l=i.get("shape",c,a,d),k=i.getImgSrc(c,a,d),t=!0,m=i.getScale(c,a,d),g=o.getIcon(),y=g?!0:!1,r=b.orientation,w=b.map.simulateOrientation&&r!==void 0;g||(g={});if(!l&&k)t=!1;else if(!i.shapes[l]&&!y)l=i.defaultShapeType;l=this._getIconUrl(t,l,k);if(w){if(j.isObject(r))r=r.heading;
r=Math.round(e.radToDeg(r));r<0&&(r=360+r);l&&(l=s(b,l))}if(l)g.url=l;if(l=t?i.getSize(c,a,d):i.getImgSize(c,a,d)){if(a=t?[l[0]/2,l[1]/2]:i.getAnchor(c,a,d,l),g.size=new p.Size(m*l[0],m*l[1]),g.anchor=new p.Point(m*a[0],m*a[1]),g.scaledSize=new p.Size(m*l[0],m*l[1]),w)g.origin=new p.Point(0,l[1]*r),g.scaledSize.height*=360}else y&&(m=i.get("rScale",c,a,d),m!==void 0&&(g.size.width*=m,g.size.height*=m,g.anchor.x*=m,g.anchor.y*=m,g.scaledSize.width*=m,g.scaledSize.height*=m,w&&(g.origin.y*=m)));o.setIcon(g)},
applyLineStyle:function(b,c){var a=c.line,e=i.getSpecificShapeStyle(c.lines,this.specificStyleIndex),j=b.baseShapes,l=i.get("stroke",c,a,e),k=i.get("strokeOpacity",c,a,e),p=i.get("strokeWidth",c,a,e);d.forEach(j,function(a){var b={};if(l)b.strokeColor=o(l);if(k!==void 0)b.strokeOpacity=k;if(p!==void 0)b.strokeWeight=p;a.setOptions(b)})},applyPolygonStyle:function(b,c){var a=c.polygon,e=b.baseShapes[0],d=i.get("fill",c,a),l=i.get("fillOpacity",c,a),j=i.get("stroke",c,a),k=i.get("strokeOpacity",c,a),
a=i.get("strokeWidth",c,a),m={};if(d)m.fillColor=o(d);if(l!==void 0)m.fillOpacity=l;if(j)m.strokeColor=o(j);if(k!==void 0)m.strokeOpacity=k;if(a!==void 0)m.strokeWeight=a;e.setOptions(m)},remove:function(b){d.forEach(b.baseShapes,function(b){b.setMap(null)})},show:function(b,c){d.forEach(b.baseShapes,function(a){a.setMap(c?b.map.engine.gmap:null)})},makeText:function(){},setCoords:function(b,c){c.baseShapes[0].setPosition(new p.LatLng(b[1],b[0]))},setOrientation:function(b,c){if(c.map.simulateOrientation){var a=
c.baseShapes[0],d=a.getIcon(),i=Math.round(e.radToDeg(b)),j=d.size,k=c.reg.url;k||(k=s(c,d.url));i<0&&(i=360+i);d.url=k;d.origin=new p.Point(0,j.height*i);d.scaledSize.height=360*j.height;a.setIcon(d)}}});c.init=function(){p=google.maps};return c})},"djeo/_tiles":function(){define("djeo/_tiles",[],function(){var c=["WebTiles",{url:"http://[a,b,c].tile.openstreetmap.org"}];return{webtiles:["WebTiles",{}],roadmap:c,osm:c,openstreetmap:c,"osm.org":c,"openstreetmap.org":c,"mapquest-osm":["WebTiles",{url:"http://otile[1,2,3,4].mqcdn.com/tiles/1.0.0/osm"}],
"mapquest-oa":["WebTiles",{url:"http://oatile[1,2,3,4].mqcdn.com/tiles/1.0.0/sat"}],arcgis_webtiles:["WebTiles",{}]}})},"dojo/main":function(){define("dojo/main",["./_base/kernel","./has","require","./_base/sniff","./_base/lang","./_base/array","./ready","./_base/declare","./_base/connect","./_base/Deferred","./_base/json","./_base/Color","./has!dojo-firebug?./_firebug/firebug","./_base/browser","./_base/loader"],function(c,j,d,b,k,e,i){c.config.isDebug&&d(["./_firebug/firebug"]);var o=c.config.require;
o&&(o=e.map(k.isArray(o)?o:[o],function(b){return b.replace(/\./g,"/")}),c.isAsync?d(o):i(1,function(){d(o)}));return c})}}});define("djeo-gmaps/gmaps",[],1);