//>>built
require({cache:{"dojo/_base/loader":function(){define("dojo/_base/loader",["./kernel","../has","require","module","./json","./lang","./array"],function(a,h,e,b,m,d,o){var j=function(a){return a.replace(/\./g,"/")},n=/\/\/>>built/,q=[],i=[],f,s=function(a){f[a.mid]=1;for(var c,b,d=a.deps||[],i=0;i<d.length;i++)if(b=d[i],!(c=f[b.mid]))if(c===0||!s(b))return f[a.mid]=0,!1;return!0},c=function(){var a,c;f={};for(c in z)if(a=z[c],a.executed||a.noReqPluginCheck)f[c]=1;else{if(a.noReqPluginCheck!==0)a.noReqPluginCheck=
/loadInit\!/.test(c)||/require\!/.test(c)?1:0;a.noReqPluginCheck?f[c]=1:a.injected!==t&&(f[c]=0)}for(var b=0,d=i.length;b<d;b++)if(a=i[b],!(c=f[a.mid]))if(c===0||!s(a))return;g.holdIdle();a=q;q=[];o.forEach(a,function(a){a(1)});g.releaseIdle()},k=function(c,b,d){var i=/\(|\)/g,f=1;for(i.lastIndex=b;b=i.exec(c);)if(b[0]==")"?f-=1:f+=1,f==0)break;if(f!=0)throw"unmatched paren around character "+i.lastIndex+" in: "+c;return[a.trim(c.substring(d,i.lastIndex))+";\n",i.lastIndex]},v=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,
l=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,r=/(^|\s)(require|define)\s*\(/m,A=function(a,c){var b,d,i,f=[],q=[];b=[];for(c=c||a.replace(v,function(a){l.lastIndex=r.lastIndex=0;return l.test(a)||r.test(a)?"":a});b=l.exec(c);)d=l.lastIndex,i=d-b[0].length,d=k(c,d,i),b[2]=="loadInit"?f.push(d[0]):q.push(d[0]),l.lastIndex=d[1];b=f.concat(q);return b.length||!r.test(c)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 && dojo.loadInit("),b.join(""),
b]:0},g=e.initSyncLoader(function(a,b,d){q.push(d);o.forEach(a.split(","),function(a){a=u(a,b.module);i.push(a);x(a)});c()},c,function(c,b){var d,i,f=[],k=[];if(n.test(b)||!(d=A(b)))return 0;i=c.mid+"-*loadInit";for(var q in u("dojo",c).result.scopeMap)f.push(q),k.push('"'+q+'"');return"// xdomain rewrite of "+c.path+"\ndefine('"+i+"',{\n\tnames:"+a.toJson(f)+",\n\tdef:function("+f.join(",")+"){"+d[1]+"}});\n\ndefine("+a.toJson(f.concat(["dojo/loadInit!"+i]))+", function("+f.join(",")+"){\n"+d[0]+
"});"}),y=g.sync,t=g.arrived,p=g.nonmodule,F=g.executing,B=g.executed,w=g.syncExecStack,z=g.modules,C=g.execQ,u=g.getModule,x=g.injectModule,D=g.setArrived,G=g.signal,H=g.finishExec,I=g.execModule,E=g.getLegacyMode;a.provide=function(a){var c=w[0],b=d.mixin(u(j(a),e.module),{executed:F,result:d.getObject(a,!0)});D(b);if(c)(c.provides||(c.provides=[])).push(function(){b.result=d.getObject(a);delete b.provides;b.executed!==B&&H(b)});return b.result};h.add("config-publishRequireResult",1,0,0);a.require=
function(a,c){var b=function(a,b){var c=u(j(a),e.module);if(w.length&&w[0].finish)w[0].finish.push(a);else{if(c.executed)return c.result;b&&(c.result=p);var d=E();x(c);d=E();c.executed!==B&&c.injected===t&&(g.holdIdle(),I(c),g.releaseIdle());if(c.executed)return c.result;d==y?c.cjs?C.unshift(c):w.length&&(w[0].finish=[a]):C.push(c)}}(a,c);h("config-publishRequireResult")&&!d.exists(a)&&b!==void 0&&d.setObject(a,b);return b};a.loadInit=function(a){a()};a.registerModulePath=function(a,c){var b={};b[a.replace(/\./g,
"/")]=c;e({paths:b})};a.platformRequire=function(c){for(var c=(c.common||[]).concat(c[a._name]||c["default"]||[]),b;c.length;)d.isArray(b=c.shift())?a.require.apply(a,b):a.require(b)};a.requireIf=a.requireAfterIf=function(c,b,d){c&&a.require(b,d)};a.requireLocalization=function(c,a,b){e(["../i18n"],function(d){d.getLocalization(c,a,b)})};return{extractLegacyApiApplications:A,require:g.dojoRequirePlugin,loadInit:function(d,f,k){f([d],function(d){f(d.names,function(){for(var s="",m=[],g=0;g<arguments.length;g++)s+=
"var "+d.names[g]+"= arguments["+g+"]; ",m.push(arguments[g]);eval(s);var e=f.module,v=[],s={},h=[],l,g={provide:function(c){c=j(c);c=u(c,e);c!==e&&D(c)},require:function(c,a){c=j(c);a&&(u(c,e).result=p);h.push(c)},requireLocalization:function(c,b,d){v.length||(v=["dojo/i18n"]);d=(d||a.locale).toLowerCase();c=j(c)+"/nls/"+(/root/i.test(d)?"":d+"/")+j(b);u(c,e).isXd&&v.push("dojo/i18n!"+c)},loadInit:function(c){c()}};try{for(l in g)s[l]=a[l],a[l]=g[l];d.def.apply(null,m)}catch(n){G("error",[{src:b.id,
id:"failedDojoLoadInit"},n])}finally{for(l in g)a[l]=s[l]}h.length&&v.push("dojo/require!"+h.join(","));q.push(k);o.forEach(h,function(c){c=u(c,f.module);i.push(c);x(c)});c()})})}}})},"dojo/io/script":function(){define("dojo/io/script",["../main"],function(a){a.getObject("io",!0,a);var h=a.isIE?"onreadystatechange":"load",e=/complete|loaded/;a.io.script={get:function(b){var m=this._makeScriptDeferred(b),d=m.ioArgs;a._ioAddQueryToUrl(d);a._ioNotifyStart(m);if(this._canAttach(d)){var o=this.attach(d.id,
d.url,b.frameDoc);if(!d.jsonp&&!d.args.checkString)var j=a.connect(o,h,function(b){if(b.type=="load"||e.test(o.readyState))a.disconnect(j),d.scriptLoaded=b})}a._ioWatch(m,this._validCheck,this._ioCheck,this._resHandle);return m},attach:function(b,m,d){var d=d||a.doc,e=d.createElement("script");e.type="text/javascript";e.src=m;e.id=b;e.async=!0;e.charset="utf-8";return d.getElementsByTagName("head")[0].appendChild(e)},remove:function(b,e){a.destroy(a.byId(b,e));this["jsonp_"+b]&&delete this["jsonp_"+
b]},_makeScriptDeferred:function(b){var e=a._ioSetArgs(b,this._deferredCancel,this._deferredOk,this._deferredError),d=e.ioArgs;d.id=a._scopeName+"IoScript"+this._counter++;d.canDelete=!1;d.jsonp=b.callbackParamName||b.jsonp;if(d.jsonp)d.query=d.query||"",d.query.length>0&&(d.query+="&"),d.query+=d.jsonp+"="+(b.frameDoc?"parent.":"")+a._scopeName+".io.script.jsonp_"+d.id+"._jsonpCallback",d.frameDoc=b.frameDoc,d.canDelete=!0,e._jsonpCallback=this._jsonpCallback,this["jsonp_"+d.id]=e;return e},_deferredCancel:function(b){b.canceled=
!0;b.ioArgs.canDelete&&a.io.script._addDeadScript(b.ioArgs)},_deferredOk:function(b){b=b.ioArgs;b.canDelete&&a.io.script._addDeadScript(b);return b.json||b.scriptLoaded||b},_deferredError:function(b,e){e.ioArgs.canDelete&&(b.dojoType=="timeout"?a.io.script.remove(e.ioArgs.id,e.ioArgs.frameDoc):a.io.script._addDeadScript(e.ioArgs));return b},_deadScripts:[],_counter:1,_addDeadScript:function(b){a.io.script._deadScripts.push({id:b.id,frameDoc:b.frameDoc});b.frameDoc=null},_validCheck:function(){var b=
a.io.script,e=b._deadScripts;if(e&&e.length>0){for(var d=0;d<e.length;d++)b.remove(e[d].id,e[d].frameDoc),e[d].frameDoc=null;a.io.script._deadScripts=[]}return!0},_ioCheck:function(a){a=a.ioArgs;if(a.json||a.scriptLoaded&&!a.args.checkString)return!0;return(a=a.args.checkString)&&eval("typeof("+a+") != 'undefined'")},_resHandle:function(b){a.io.script._ioCheck(b)?b.callback(b):b.errback(Error("inconceivable dojo.io.script._resHandle error"))},_canAttach:function(){return!0},_jsonpCallback:function(a){this.ioArgs.json=
a}};return a.io.script})},"dojo/_base/browser":function(){require.has&&require.has.add("config-selectorEngine","acme");define("dojo/_base/browser",["../ready","./kernel","./connect","./unload","./window","./event","./html","./NodeList","../query","./xhr","./fx"],function(a){return a})},"djeo-ymaps/Engine":function(){define("djeo-ymaps/Engine",["require","dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/aspect","dojo/io/script","djeo/Engine","./Placemark","djeo/_tiles"],function(a,h,
e,b,m,d,o,j,n){function q(c,a,b,d){return{remove:function(){c.events.remove(a,b,d)}}}var i=window.ymaps,f={roadmap:"map",satellite:"satellite",hybrid:"hybrid"},s={click:"click",mouseover:"mouseenter",mouseout:"mouseleave"},n=e.mixin(e.mixin({},n),f);return h([o],{ymap:null,constructor:function(){this._require=a;e.mixin(this.ignoredDependencies,{Highlight:1,Tooltip:1});this._supportedLayers=n;this._initBasicFactories(new j({map:this.map,engine:this}))},initialize:function(c){if(i){var b=this.map;b.projection=
"EPSG:4326";b=new i.Map(b.container,{minZoom:b.minZoom,maxZoom:b.maxZoom,propagateEvents:!0,center:[0,0],zoom:0,type:null});b.behaviors.disable(["drag","dblClickZoom"]);this.ymap=b;this.initialized=!0;c()}else if(this._initializing)m.after(this,"_initializing",e.hitch(this,function(){this.initialize(c)}));else{this._initializing=function(){};var b={coordorder:"longlat",load:"package.full",lang:"ru-RU"},f=this.map.ymapsKey||a.rawConfig.ymapsKey;if(f)b.key=f;d.get({url:"http://api-maps.yandex.ru/2.0/",
content:b,load:e.hitch(this,function(){ymaps.ready(e.hitch(this,function(){j.init();i=ymaps;this._initializing();delete this._initializing;this.initialize(c)}))})})}},createContainer:function(){},appendChild:function(c){this.ymap.geoObjects.add(c)},onForFeature:function(c,a,b,d){b=this.normalizeCallback(c,a,b,d);c=c.baseShapes[0];c.events.add(s[a],b,d);return[[c,s[a],b,d]]},disconnect:function(c){b.forEach(c,function(c){c[0].events.remove(c[1],c[2],c[3])})},onForMap:function(c,a,b){var d=function(c){a.call(b,
{mapCoords:c.get("coordPosition"),nativeEvent:c})};this.ymap.events.add(c,d);return q(this.ymap,c,d)},_on_zoom_changed:function(c,a,b){c=function(c){c.get("newZoom")!=c.get("oldZoom")&&a.call(b)};this.ymap.events.add("boundschange",c);return q(this.ymap,"boundschange",c)},_on_extent_changed:function(c,a,b){this.ymap.events.add("boundschange",a,b);return q(this.ymap,"boundschange",a,b)},zoomTo:function(c){this.ymap.setBounds([[c[0],c[1]],[c[2],c[3]]])},destroy:function(){},enableLayer:function(c,a){if(e.isString(c)){var b=
c.toLowerCase();b in f?a&&this.ymap.setType("yandex#"+f[b]):this.inherited(arguments)}else this.inherited(arguments)},getLayerModuleId:function(c){if(c.toLowerCase()in f)return null;return this.inherited(arguments)},_setCamera:function(c){this.ymap.setCenter(c.center,c.zoom)},_set_center:function(c){this.ymap.setCenter(c)},_get_center:function(){return this.ymap.getCenter()},_set_zoom:function(c){this.ymap.setZoom(c)},_get_zoom:function(){return this.ymap.getZoom()},_get_extent:function(){var c=this.ymap.getBounds(),
a=c[0],c=c[1];return[a[0],a[1],c[0],c[1]]},_appendDiv:function(c){this.map.container.children[0].appendChild(c)}})})},"dojo/_base/NodeList":function(){define("dojo/_base/NodeList",["./kernel","../query","./array","./html","../NodeList-dom"],function(a,h,e){var h=h.NodeList,b=h.prototype;b.connect=h._adaptAsForEach(function(){return a.connect.apply(this,arguments)});b.coords=h._adaptAsMap(a.coords);h.events=["blur","focus","change","click","error","keydown","keypress","keyup","load","mousedown","mouseenter",
"mouseleave","mousemove","mouseout","mouseover","mouseup","submit"];e.forEach(h.events,function(a){var d="on"+a;b[d]=function(a,b){return this.connect(d,a,b)}});a.NodeList=h;return a.NodeList})},"djeo-ymaps/Placemark":function(){define("djeo-ymaps/Placemark",["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Color","djeo/util/_base","djeo/common/Placemark"],function(a,h,e,b,m,d){function o(a,i,f,e){var a=d.get("stroke",i,f,e),c=d.get("strokeWidth",i,f,e),i=d.get("strokeOpacity",
i,f,e);if(a||c!==void 0||i!==void 0){f={};if(a)f.strokeColor=(new b(a)).toHex();if(i!==void 0)f.strokeOpacity=i;if(c!==void 0)f.strokeWidth=c;return f}}function j(a,b){var d=b.match(/\b\w+\.\w{3,4}$/)[0],e=d.split("."),b=b.substr(0,b.length-e[0].length-e[1].length-1)+e[0]+"_"+e[1]+"/"+d;return a.reg.url=b}var n=window.YMaps,a=a([d],{constructor:function(a){h.mixin(this,a)},makePoint:function(a,b){return new n.Placemark(b,{hasBalloon:!1,hideIconOnBalloonOpen:!1})},makeLineString:function(a,b){return this._makeLineString(b)},
_makeLineString:function(a){return new n.Polyline(a,{hasBalloon:!1})},makePolygon:function(a,b){return this._makePolygon(b)},_makePolygon:function(a){return new n.Polygon(a,{hasBalloon:!1})},makeMultiLineString:function(a,b){var d=new n.GeoObjectCollection;e.forEach(b,function(a){d.add(this._makeLineString(a))},this);return d},makeMultiPolygon:function(a,b){var d=new n.GeoObjectCollection;e.forEach(b,function(a){d.add(this._makePolygon(a))},this);return d},applyPointStyle:function(a,b){var f=b.point,
e=d.getSpecificShapeStyle(b.points,this.specificStyleIndex),c=a.baseShapes[0],k=d.get("shape",b,f,e),n=d.getImgSrc(b,f,e),l=!0,r=d.getScale(b,f,e),o=c.options.get("iconImageHref"),g=a.orientation,y=a.map.simulateOrientation&&g!==void 0,t={};if(!k&&n)l=!1;else if(!d.shapes[k]&&!o)k=d.defaultShapeType;var p=l?d.getSize(b,f,e):d.getImgSize(b,f,e);if(p)f=l?[p[0]/2,p[1]/2]:d.getAnchor(b,f,e,p),t.iconImageSize=[r*p[0],r*p[1]],t.iconImageOffset=[-r*f[0],-r*f[1]];else if(o&&(r=d.get("rScale",b,f,e),r!==void 0))p=
c.options.get("iconImageSize"),f=c.options.get("iconImageOffset"),t.iconImageSize=[r*p[0],r*p[1]],t.iconImageOffset=[r*f[0],r*f[1]];k=this._getIconUrl(l,k,n);if(y){if(h.isObject(g))g=g.heading;g=Math.round(m.radToDeg(g));g<0&&(g=360+g);t.iconImageClipRect=[[0,p[1]*g],[p[0],p[1]*(g+1)]];k&&(k=j(a,k))}if(k)t.iconImageHref=k;c.options.set(t)},applyLineStyle:function(a,b){var e=b.line,h=d.getSpecificShapeStyle(b.lines,this.specificStyleIndex),c=a.baseShapes[0];(e=o(c,b,e,h))&&c.options.set(e)},applyPolygonStyle:function(a,
e){var f=e.polygon,h=a.baseShapes[0],c=d.get("fill",e,f),k=d.get("fillOpacity",e,f),f=o(h,e,f);if(c||k!==void 0){f=f||{};if(c)f.fillColor=(new b(c)).toHex();if(k!==void 0)f.fillOpacity=k}f&&h.options.set(f)},remove:function(){},show:function(a,b){b?this.engine.ymap.geoObjects.add(a.baseShapes[0]):this.engine.ymap.geoObjects.remove(a.baseShapes[0])},makeText:function(){},setCoords:function(a,b){b.baseShapes[0].geometry.setCoordinates(a)},setOrientation:function(a,b){if(b.map.simulateOrientation){var d=
b.baseShapes[0],e=Math.round(m.radToDeg(a)),c=d.options.get("iconImageSize"),h=b.reg.url;h||(h=j(b,d.options.get("iconImageHref")));e<0&&(e=360+e);d.options.set({iconImageHref:h,iconImageClipRect:[[0,c[1]*e],[c[0],c[1]*(e+1)]]})}}});a.init=function(){n=ymaps};return a})},"djeo/_tiles":function(){define("djeo/_tiles",[],function(){var a=["WebTiles",{url:"http://[a,b,c].tile.openstreetmap.org"}];return{webtiles:["WebTiles",{}],roadmap:a,osm:a,openstreetmap:a,"osm.org":a,"openstreetmap.org":a,"mapquest-osm":["WebTiles",
{url:"http://otile[1,2,3,4].mqcdn.com/tiles/1.0.0/osm"}],"mapquest-oa":["WebTiles",{url:"http://oatile[1,2,3,4].mqcdn.com/tiles/1.0.0/sat"}],arcgis_webtiles:["WebTiles",{}]}})},"dojo/main":function(){define("dojo/main",["./_base/kernel","./has","require","./_base/sniff","./_base/lang","./_base/array","./ready","./_base/declare","./_base/connect","./_base/Deferred","./_base/json","./_base/Color","require","./_base/browser","./_base/loader"],function(a,h,e,b,m,d,o){a.config.isDebug&&e(["./_firebug/firebug"]);
var j=a.config.require;j&&(j=d.map(m.isArray(j)?j:[j],function(a){return a.replace(/\./g,"/")}),a.isAsync?e(j):o(1,function(){e(j)}));return a})},"djeo-ymaps/Navigation":function(){define("djeo-ymaps/Navigation",["dojo/_base/declare"],function(a){function h(a){a.get("newZoom")!=a.get("oldZoom")&&this._onZoom()}return a(null,{enable:function(a){a===void 0&&(a=!0);var b=this.map.engine.ymap;a?(b.behaviors.enable(["drag","dblClickZoom","scrollZoom"]),b.events.add("boundschange",h,this)):(b.behaviors.disable(["scrollZoom",
"dblClickZoom","drag"]),b.events.remove("boundschange",h,this))}})})}}});define("djeo-ymaps/ymaps",[],1);