//>>built
require({cache:{"djeo-ge/Navigation":function(){define("djeo-ge/Navigation",["dojo/_base/declare"],function(d){return d(null,{enable:function(d){d===void 0&&(d=!0);this.map.engine.ge.getOptions().setMouseNavigationEnabled(d)}})})},"dojo/_base/loader":function(){define("dojo/_base/loader",["./kernel","../has","require","module","./json","./lang","./array"],function(d,i,f,e,j,g,p){var k=function(a){return a.replace(/\./g,"/")},s=/\/\/>>built/,o=[],q=[],n,m=function(a){n[a.mid]=1;for(var c,b,h=a.deps||
[],d=0;d<h.length;d++)if(b=h[d],!(c=n[b.mid]))if(c===0||!m(b))return n[a.mid]=0,!1;return!0},a=function(){var a,c;n={};for(c in x)if(a=x[c],a.executed||a.noReqPluginCheck)n[c]=1;else{if(a.noReqPluginCheck!==0)a.noReqPluginCheck=/loadInit\!/.test(c)||/require\!/.test(c)?1:0;a.noReqPluginCheck?n[c]=1:a.injected!==y&&(n[c]=0)}for(var b=0,h=q.length;b<h;b++)if(a=q[b],!(c=n[a.mid]))if(c===0||!m(a))return;l.holdIdle();a=o;o=[];p.forEach(a,function(a){a(1)});l.releaseIdle()},c=function(a,c,b){var h=/\(|\)/g,
e=1;for(h.lastIndex=c;c=h.exec(a);)if(c[0]==")"?e-=1:e+=1,e==0)break;if(e!=0)throw"unmatched paren around character "+h.lastIndex+" in: "+a;return[d.trim(a.substring(b,h.lastIndex))+";\n",h.lastIndex]},b=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,h=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,t=/(^|\s)(require|define)\s*\(/m,r=function(a,e){var d,g,r,j=[],f=[];d=[];for(e=e||a.replace(b,function(a){h.lastIndex=t.lastIndex=0;return h.test(a)||
t.test(a)?"":a});d=h.exec(e);)g=h.lastIndex,r=g-d[0].length,g=c(e,g,r),d[2]=="loadInit"?j.push(g[0]):f.push(g[0]),h.lastIndex=g[1];d=j.concat(f);return d.length||!t.test(e)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 && dojo.loadInit("),d.join(""),d]:0},l=f.initSyncLoader(function(c,b,h){o.push(h);p.forEach(c.split(","),function(a){a=u(a,b.module);q.push(a);w(a)});a()},a,function(a,c){var b,h,e=[],g=[];if(s.test(c)||!(b=r(c)))return 0;h=a.mid+"-*loadInit";for(var t in u("dojo",a).result.scopeMap)e.push(t),
g.push('"'+t+'"');return"// xdomain rewrite of "+a.path+"\ndefine('"+h+"',{\n\tnames:"+d.toJson(e)+",\n\tdef:function("+e.join(",")+"){"+b[1]+"}});\n\ndefine("+d.toJson(e.concat(["dojo/loadInit!"+h]))+", function("+e.join(",")+"){\n"+b[0]+"});"}),E=l.sync,y=l.arrived,z=l.nonmodule,F=l.executing,A=l.executed,v=l.syncExecStack,x=l.modules,B=l.execQ,u=l.getModule,w=l.injectModule,C=l.setArrived,G=l.signal,H=l.finishExec,I=l.execModule,D=l.getLegacyMode;d.provide=function(a){var c=v[0],b=g.mixin(u(k(a),
f.module),{executed:F,result:g.getObject(a,!0)});C(b);if(c)(c.provides||(c.provides=[])).push(function(){b.result=g.getObject(a);delete b.provides;b.executed!==A&&H(b)});return b.result};i.add("config-publishRequireResult",1,0,0);d.require=function(a,c){var b=function(a,c){var b=u(k(a),f.module);if(v.length&&v[0].finish)v[0].finish.push(a);else{if(b.executed)return b.result;c&&(b.result=z);var h=D();w(b);h=D();b.executed!==A&&b.injected===y&&(l.holdIdle(),I(b),l.releaseIdle());if(b.executed)return b.result;
h==E?b.cjs?B.unshift(b):v.length&&(v[0].finish=[a]):B.push(b)}}(a,c);i("config-publishRequireResult")&&!g.exists(a)&&b!==void 0&&g.setObject(a,b);return b};d.loadInit=function(a){a()};d.registerModulePath=function(a,c){var b={};b[a.replace(/\./g,"/")]=c;f({paths:b})};d.platformRequire=function(a){for(var a=(a.common||[]).concat(a[d._name]||a["default"]||[]),b;a.length;)g.isArray(b=a.shift())?d.require.apply(d,b):d.require(b)};d.requireIf=d.requireAfterIf=function(a,b,c){a&&d.require(b,c)};d.requireLocalization=
function(a,b,c){f(["../i18n"],function(h){h.getLocalization(a,b,c)})};return{extractLegacyApiApplications:r,require:l.dojoRequirePlugin,loadInit:function(b,c,h){c([b],function(b){c(b.names,function(){for(var g="",t=[],r=0;r<arguments.length;r++)g+="var "+b.names[r]+"= arguments["+r+"]; ",t.push(arguments[r]);eval(g);var j=c.module,f=[],g={},l=[],i,r={provide:function(a){a=k(a);a=u(a,j);a!==j&&C(a)},require:function(a,b){a=k(a);b&&(u(a,j).result=z);l.push(a)},requireLocalization:function(a,b,c){f.length||
(f=["dojo/i18n"]);c=(c||d.locale).toLowerCase();a=k(a)+"/nls/"+(/root/i.test(c)?"":c+"/")+k(b);u(a,j).isXd&&f.push("dojo/i18n!"+a)},loadInit:function(a){a()}};try{for(i in r)g[i]=d[i],d[i]=r[i];b.def.apply(null,t)}catch(n){G("error",[{src:e.id,id:"failedDojoLoadInit"},n])}finally{for(i in r)d[i]=g[i]}l.length&&f.push("dojo/require!"+l.join(","));o.push(h);p.forEach(l,function(a){a=u(a,c.module);q.push(a);w(a)});a()})})}}})},"dojo/io/script":function(){define("dojo/io/script",["../main"],function(d){d.getObject("io",
!0,d);var i=d.isIE?"onreadystatechange":"load",f=/complete|loaded/;d.io.script={get:function(e){var j=this._makeScriptDeferred(e),g=j.ioArgs;d._ioAddQueryToUrl(g);d._ioNotifyStart(j);if(this._canAttach(g)){var p=this.attach(g.id,g.url,e.frameDoc);if(!g.jsonp&&!g.args.checkString)var k=d.connect(p,i,function(e){if(e.type=="load"||f.test(p.readyState))d.disconnect(k),g.scriptLoaded=e})}d._ioWatch(j,this._validCheck,this._ioCheck,this._resHandle);return j},attach:function(e,j,g){var g=g||d.doc,f=g.createElement("script");
f.type="text/javascript";f.src=j;f.id=e;f.async=!0;f.charset="utf-8";return g.getElementsByTagName("head")[0].appendChild(f)},remove:function(e,f){d.destroy(d.byId(e,f));this["jsonp_"+e]&&delete this["jsonp_"+e]},_makeScriptDeferred:function(e){var f=d._ioSetArgs(e,this._deferredCancel,this._deferredOk,this._deferredError),g=f.ioArgs;g.id=d._scopeName+"IoScript"+this._counter++;g.canDelete=!1;g.jsonp=e.callbackParamName||e.jsonp;if(g.jsonp)g.query=g.query||"",g.query.length>0&&(g.query+="&"),g.query+=
g.jsonp+"="+(e.frameDoc?"parent.":"")+d._scopeName+".io.script.jsonp_"+g.id+"._jsonpCallback",g.frameDoc=e.frameDoc,g.canDelete=!0,f._jsonpCallback=this._jsonpCallback,this["jsonp_"+g.id]=f;return f},_deferredCancel:function(e){e.canceled=!0;e.ioArgs.canDelete&&d.io.script._addDeadScript(e.ioArgs)},_deferredOk:function(e){e=e.ioArgs;e.canDelete&&d.io.script._addDeadScript(e);return e.json||e.scriptLoaded||e},_deferredError:function(e,f){f.ioArgs.canDelete&&(e.dojoType=="timeout"?d.io.script.remove(f.ioArgs.id,
f.ioArgs.frameDoc):d.io.script._addDeadScript(f.ioArgs));return e},_deadScripts:[],_counter:1,_addDeadScript:function(e){d.io.script._deadScripts.push({id:e.id,frameDoc:e.frameDoc});e.frameDoc=null},_validCheck:function(){var e=d.io.script,f=e._deadScripts;if(f&&f.length>0){for(var g=0;g<f.length;g++)e.remove(f[g].id,f[g].frameDoc),f[g].frameDoc=null;d.io.script._deadScripts=[]}return!0},_ioCheck:function(e){e=e.ioArgs;if(e.json||e.scriptLoaded&&!e.args.checkString)return!0;return(e=e.args.checkString)&&
eval("typeof("+e+") != 'undefined'")},_resHandle:function(e){d.io.script._ioCheck(e)?e.callback(e):e.errback(Error("inconceivable dojo.io.script._resHandle error"))},_canAttach:function(){return!0},_jsonpCallback:function(e){this.ioArgs.json=e}};return d.io.script})},"dojo/_base/browser":function(){require.has&&require.has.add("config-selectorEngine","acme");define("dojo/_base/browser",["../ready","./kernel","./connect","./unload","./window","./event","./html","./NodeList","../query","./xhr","./fx"],
function(d){return d})},"djeo-ge/Placemark":function(){define("djeo-ge/Placemark",["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Color","djeo/_base","djeo/common/Placemark","djeo/util/_base","./_base"],function(d,i,f,e,j,g,p,k){var d=d([g],{constructor:function(a){i.mixin(this,a)},init:function(){this.ge=this.map.engine.ge},render:function(a,c,b){google.earth.executeBatch(this.map.engine.ge,i.hitch(this,function(){this._render(a,c,b)}))},createPlacemark:function(){var a=this.ge.createPlacemark("");
a.setStyleSelector(this.ge.createStyle(""));return a},makePoint:function(a,c){var b=this.createPlacemark(),h=this.ge.createPoint("");h.setLatLngAlt(c[1],c[0],m(a,c));this._setGeometryAttributes(a,h);b.setGeometry(h);return b},makeLineString:function(a,c){var b=this.createPlacemark(),h=this.ge.createLineString("");this._makeLineString(a,h,c);this._setGeometryAttributes(a,h);b.setGeometry(h);return b},_makeLineString:function(a,c,b){f.forEach(b,function(b){c.getCoordinates().pushLatLngAlt(b[1],b[0],
m(a,b))},this)},makePolygon:function(a,c){var b=this.createPlacemark(),h=this.ge.createPolygon("");this._makePolygon(a,h,c);this._setGeometryAttributes(a,h);b.setGeometry(h);return b},_makePolygon:function(a,c,b){f.forEach(b,function(b,e){var d=this.ge.createLinearRing("");f.forEach(b,function(b){d.getCoordinates().pushLatLngAlt(b[1],b[0],m(a,b))});e?c.getInnerBoundaries().appendChild(d):c.setOuterBoundary(d)},this)},makeMultiLineString:function(a,c){var b=this.createPlacemark(),h=this.ge.createMultiGeometry("");
this._setGeometryAttributes(a,h);b.setGeometry(h);f.forEach(c,function(b){var c=this.ge.createLineString("");this._makeLineString(a,c,b);h.getGeometries().appendChild(c)},this);return b},makeMultiPolygon:function(a,c){var b=this.createPlacemark(),h=this.ge.createMultiGeometry("");this._setGeometryAttributes(a,h);b.setGeometry(h);f.forEach(c,function(b){var c=this.ge.createPolygon("");this._makePolygon(a,c,b);h.getGeometries().appendChild(c)},this);return b},_setGeometryAttributes:function(a,c){var b=
j.getTraversedAttr(a,"altitudeMode");k.altitudeModes[b]&&c.setAltitudeMode(this.ge[k.altitudeModes[b]]);b=j.getTraversedAttr(a,"extrude");b!==void 0&&c.setExtrude(b);a.tessellate!=void 0&&c.setTessellate(a.tessellate)},applyPointStyle:function(a,c){var b=c.point,h=g.getSpecificShapeStyle(c.points,this.specificStyleIndex),e=a.baseShapes[0],d=g.get("shape",c,b,h),f=g.getImgSrc(c,b,h),j=!0,n=g.getScale(c,b,h),o=e.getStyleSelector(),e=a.reg.kmlIconScale!==void 0?!0:!1;if(!d&&f)j=!1;else if(!g.shapes[d]&&
!e)d=g.defaultShapeType;o=o.getIconStyle();if(d=j&&d?s+g.shapes[d]:this._getImageUrl(f))f=this.ge.createIcon(""),f.setHref(d),o.setIcon(f);var d=j?g.getSize(c,b,h):g.getImgSize(c,b,h),m;d?(m=j?n*Math.max(d[0],d[1])/k.shapeSize:n,a.reg.kmlIconScale=m):e&&(n=g.get("rScale",c,b,h),n!==void 0&&(m=n*a.reg.kmlIconScale));o.setScale(m);if(!e&&(m=a.orientation,m!==void 0)){if(i.isObject(m))m=m.heading;o.setHeading(p.radToDeg(m))}j&&q(o,c,b,h,!0)},applyLineStyle:function(a,c){var b=c.line,h=g.getSpecificShapeStyle(c.lines,
this.specificStyleIndex),d=a.baseShapes[0].getStyleSelector();n(d,c,b,h);a.extrude&&q(d,c,b,h)},applyPolygonStyle:function(a,c){var b=c.polygon,h=a.baseShapes[0].getStyleSelector();q(h,c,b);n(h,c,b)},remove:function(a){f.forEach(a.baseShapes,function(a){a.getParentNode().getFeatures().removeChild(a)})},show:function(a,c){a.baseShapes[0].setVisibility(c)},makeText:function(a,c){if(a.getCoordsType()=="Point"){var b=g.get("text",c,c.point);if(b){var h=a.baseShapes[0],d=b.label||this._getLabel(a,b);if(d)h.setName(d),
h=h.getStyleSelector().getLabelStyle(),b.fill&&h.getColor().set(o(b.fill,1)),b.geScale&&h.setScale(b.geScale),a.textShapes=!0}}},setCoords:function(a,c){var b=c.baseShapes[0].getGeometry();a.length==3?b.setLatLngAlt(a[1],a[0],a[2]):b.setLatLng(a[1],a[0])},setOrientation:function(a,c){c.baseShapes[0].getStyleSelector().getIconStyle().setHeading(p.radToDeg(a))}}),s=function(a){for(var c=a.match(/\.\.\//g),b=c=c?c.length:0,d=p.baseUrl.length-1;c;)d--,p.baseUrl.charAt(d)=="/"&&c--;return p.baseUrl.substring(0,
d)+"/"+a.substring(3*b)}(g.shapeIconsUrl),o=function(a,c){rgba=(new e(a)).toRgba();rgba[3]=Math.round(255*c);var b=f.map(rgba,function(a){a=a.toString(16);return a.length<2?"0"+a:a});return b[3]+b[2]+b[1]+b[0]},q=function(a,c,b,d,e){var f=g.get("fill",c,b,d),c=g.get("fillOpacity",c,b,d);if(f||c!==void 0)a=e?a:a.getPolyStyle(),a=a.getColor(),f=f?f:[a.getR(),a.getG(),a.getB()],c=c!==void 0?c:a.getA()/255,a.set(o(f,c))},n=function(a,c,b,d){var e=g.get("stroke",c,b,d),f=g.get("strokeWidth",c,b,d),c=g.get("strokeOpacity",
c,b,d);if(e||f!==void 0||c!==void 0)a=a.getLineStyle(),b=a.getColor(),e=e?e:[b.getR(),b.getG(),b.getB()],c=c!==void 0?c:b.getA()/255,b.set(o(e,c)),f!==void 0&&a.setWidth(f)},m=function(a,c){return c.length==3?c[2]:a.height?a.height:0};return d})},"djeo-ge/_base":function(){define("djeo-ge/_base",[],function(){return{shapeSize:50,altitudeModes:{clampToGround:"ALTITUDE_CLAMP_TO_GROUND",relativeToGround:"ALTITUDE_RELATIVE_TO_GROUND",absolute:"ALTITUDE_ABSOLUTE"}}})},"dojo/DeferredList":function(){define("dojo/DeferredList",
["./_base/kernel","./_base/Deferred","./_base/array"],function(d,i,f){d.DeferredList=function(d,j,g,p){var k=[];i.call(this);var s=this;d.length===0&&!j&&this.resolve([0,[]]);var o=0;f.forEach(d,function(f,i){function m(a,c){k[i]=[a,c];o++;o===d.length&&s.resolve(k)}f.then(function(a){j?s.resolve([i,a]):m(!0,a)},function(a){g?s.reject(a):m(!1,a);if(p)return null;throw a;})})};d.DeferredList.prototype=new i;d.DeferredList.prototype.gatherResults=function(e){e=new d.DeferredList(e,!1,!0,!1);e.addCallback(function(d){var e=
[];f.forEach(d,function(d){e.push(d[1])});return e});return e};return d.DeferredList})},"dojo/_base/NodeList":function(){define("dojo/_base/NodeList",["./kernel","../query","./array","./html","../NodeList-dom"],function(d,i,f){var i=i.NodeList,e=i.prototype;e.connect=i._adaptAsForEach(function(){return d.connect.apply(this,arguments)});e.coords=i._adaptAsMap(d.coords);i.events=["blur","focus","change","click","error","keydown","keypress","keyup","load","mousedown","mouseenter","mouseleave","mousemove",
"mouseout","mouseover","mouseup","submit"];f.forEach(i.events,function(d){var f="on"+d;e[f]=function(d,e){return this.connect(f,d,e)}});d.NodeList=i;return d.NodeList})},"djeo-ge/Tooltip":function(){define("djeo-ge/Tooltip",["dojo/_base/declare"],function(d){return d(null,{init:function(){this.ge=this.map.engine.ge;this.balloon=this.ge.createHtmlStringBalloon("")},pointeroverAction:function(d){var f=d.reg.cs,e=this.balloon,f=f.info?f.info(d):this.content(d);e.setContentString(f);e.setFeature(d.baseShapes[0]);
this.ge.setBalloon(e)},pointeroutAction:function(){this.ge.setBalloon(null)}})})},"dojo/main":function(){define("dojo/main",["./_base/kernel","./has","require","./_base/sniff","./_base/lang","./_base/array","./ready","./_base/declare","./_base/connect","./_base/Deferred","./_base/json","./_base/Color","./has!dojo-firebug?./_firebug/firebug","./_base/browser","./_base/loader"],function(d,i,f,e,j,g,p){d.config.isDebug&&f(["./_firebug/firebug"]);var k=d.config.require;k&&(k=g.map(j.isArray(k)?k:[k],
function(d){return d.replace(/\./g,"/")}),d.isAsync?f(k):p(1,function(){f(k)}));return d})},"djeo-ge/Engine":function(){define("djeo-ge/Engine",["require","dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/aspect","dojo/io/script","dojo/_base/Deferred","dojo/DeferredList","djeo/Engine","./Placemark","djeo/util/_base"],function(d,i,f,e,j,g,p,k,s,o,q){var n={roadmap:1,hybrid:1,terrain:1};globeEvents={click:1,mousemove:1};var m=function(a,c){var b=q.degToRad(a[1]),d=q.degToRad(c[1]),e=q.degToRad(c[1]-
a[1]),f=q.degToRad(c[0]-a[0]),b=Math.pow(Math.sin(e/2),2)+Math.cos(b)*Math.cos(d)*Math.pow(Math.sin(f/2),2);return q.earthRadius*2*Math.atan2(Math.sqrt(b),Math.sqrt(1-b))};return i([s],{type:"ge",canRenderModels:!0,ge:null,constructor:function(){this._require=d;f.mixin(this.ignoredDependencies,{Highlight:1});this._supportedLayers=n;this._initBasicFactories(new o({map:this.map}))},initialize:function(a){window.google?google.load("earth","1",{callback:f.hitch(this,function(){google.earth.createInstance(this.map.container,
f.hitch(this,function(c){this.map.projection="EPSG:4326";this.ge=c;this.ge.getOptions().setMouseNavigationEnabled(!1);this.ge.getWindow().setVisibility(!0);this.initialized=!0;a()}),function(){})})}):this._initializing?j.after(this,"_initializing",f.hitch(this,function(){this.initialize(a)})):(this._initializing=function(){},g.get({url:"https://www.google.com/jsapi",load:f.hitch(this,function(){this._initializing();delete this._initializing;this.initialize(a)})}))},createContainer:function(a){var c=
this.ge.createFolder("");this.appendChild(c,a);return c},prepare:function(){this.factories.Placemark.init()},appendChild:function(a,c){c.parent.getContainer().getFeatures().appendChild(a)},getTopContainer:function(){this.ge.getFeatures();return this.ge},onForFeature:function(a,c,b,d){var e=a.baseShapes[0],b=this.normalizeCallback(a,c,b,d);google.earth.addEventListener(e,c,b);return[e,c,b]},onForMap:function(a,c,b){if(!(a in globeEvents))return{remove:function(){}};var d=this.ge.getGlobe(),e=function(a){c.call(b,
{mapCoords:[a.getLongitude(),a.getLatitude()],nativeEvent:a})};google.earth.addEventListener(d,a,e);return{remove:function(){google.earth.removeEventListener(d,a,e)}}},disconnect:function(a){google.earth.removeEventListener(a[0],a[1],a[2])},zoomTo:function(a){var c=500,b=this.map.width/this.map.height,d=(a[0]+a[2])/2,e=(a[1]+a[3])/2,f=a[3]-a[1];if(a[2]-a[0]||f)c=m([a[2],e],[a[0],e]),a=m([d,a[3]],[d,a[1]]),b=Math.min(Math.max(b,c/a),1),b=q.degToRad(45/(b+0.4)-2),a=Math.max(a,c),a=Math.min(q.degToRad(90),
b+a/(2*q.earthRadius)),c=1.5*q.earthRadius*(Math.sin(a)*Math.sqrt(1+1/Math.pow(Math.tan(b),2))-1);b=this.ge.getView().copyAsLookAt(this.ge.ALTITUDE_RELATIVE_TO_GROUND);b.setLongitude(d);b.setLatitude(e);b.setAltitude(0);b.setRange(c);this.ge.getView().setAbstractView(b)},destroy:function(){},executeBatch:function(a){google.earth.executeBatch(this.ge,a)},enableLayer:function(a,c){var b=this.ge,d=b.getLayerRoot();switch(a.toLowerCase()){case "roadmap":case "hybrid":d.enableLayerById(b.LAYER_BORDERS,
c);d.enableLayerById(b.LAYER_ROADS,c);break;case "terrain":d.enableLayerById(b.LAYER_TERRAIN,c)}},renderFeatures:function(){var a=arguments;google.earth.executeBatch(this.ge,f.hitch(this,function(){this.inherited("renderFeatures",a)}))},renderContainer:function(a,c,b){var d=new p;google.earth.executeBatch(this.ge,f.hitch(this,function(){var e=this._renderContainer(a,c,b);e&&e.length?(new k(e)).then(function(){d.resolve()}):d.resolve()}));return d},_renderContainer:function(a,c,b){if(a.visible){a.features.length==
0&&b&&a.parent.numVisibleFeatures++;var d=[];e.forEach(a.features,function(a){if(a.isContainer||a.visible)(a=a._render(c,b))&&(f.isArray(a)?e.forEach(a,function(a){d.push(a)}):d.push(a))});return d.length?d:null}}})})}}});define("djeo-ge/ge",[],1);