//>>built
require({cache:{"djeo-ge/Navigation":function(){define("djeo-ge/Navigation",["dojo/_base/declare"],function(e){return e(null,{enable:function(e){e===void 0&&(e=!0);this.map.engine.ge.getOptions().setMouseNavigationEnabled(e)}})})},"dojo/_base/loader":function(){define("dojo/_base/loader",["./kernel","../has","require","module","./json","./lang","./array"],function(e,i,g,d,j,f,p){var l=function(a){return a.replace(/\./g,"/")},w=/\/\/>>built/,o=[],n=[],m,s=function(a){m[a.mid]=1;for(var c,b,h=a.deps||
[],e=0;e<h.length;e++)if(b=h[e],!(c=m[b.mid]))if(c===0||!s(b))return m[a.mid]=0,!1;return!0},a=function(){var a,c;m={};for(c in y)if(a=y[c],a.executed||a.noReqPluginCheck)m[c]=1;else{if(a.noReqPluginCheck!==0)a.noReqPluginCheck=/loadInit\!/.test(c)||/require\!/.test(c)?1:0;a.noReqPluginCheck?m[c]=1:a.injected!==z&&(m[c]=0)}for(var b=0,h=n.length;b<h;b++)if(a=n[b],!(c=m[a.mid]))if(c===0||!s(a))return;k.holdIdle();a=o;o=[];p.forEach(a,function(a){a(1)});k.releaseIdle()},c=function(a,c,b){var h=/\(|\)/g,
d=1;for(h.lastIndex=c;c=h.exec(a);)if(c[0]==")"?d-=1:d+=1,d==0)break;if(d!=0)throw"unmatched paren around character "+h.lastIndex+" in: "+a;return[e.trim(a.substring(b,h.lastIndex))+";\n",h.lastIndex]},b=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,h=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,t=/(^|\s)(require|define)\s*\(/m,q=function(a,e){var d,f,q,g=[],j=[];d=[];for(e=e||a.replace(b,function(a){h.lastIndex=t.lastIndex=0;return h.test(a)||
t.test(a)?"":a});d=h.exec(e);)f=h.lastIndex,q=f-d[0].length,f=c(e,f,q),d[2]=="loadInit"?g.push(f[0]):j.push(f[0]),h.lastIndex=f[1];d=g.concat(j);return d.length||!t.test(e)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 && dojo.loadInit("),d.join(""),d]:0},k=g.initSyncLoader(function(c,b,h){o.push(h);p.forEach(c.split(","),function(a){a=u(a,b.module);n.push(a);x(a)});a()},a,function(a,c){var b,h,d=[],f=[];if(w.test(c)||!(b=q(c)))return 0;h=a.mid+"-*loadInit";for(var t in u("dojo",a).result.scopeMap)d.push(t),
f.push('"'+t+'"');return"// xdomain rewrite of "+a.path+"\ndefine('"+h+"',{\n\tnames:"+e.toJson(d)+",\n\tdef:function("+d.join(",")+"){"+b[1]+"}});\n\ndefine("+e.toJson(d.concat(["dojo/loadInit!"+h]))+", function("+d.join(",")+"){\n"+b[0]+"});"}),F=k.sync,z=k.arrived,A=k.nonmodule,r=k.executing,B=k.executed,v=k.syncExecStack,y=k.modules,C=k.execQ,u=k.getModule,x=k.injectModule,D=k.setArrived,G=k.signal,H=k.finishExec,I=k.execModule,E=k.getLegacyMode;e.provide=function(a){var c=v[0],b=f.mixin(u(l(a),
g.module),{executed:r,result:f.getObject(a,!0)});D(b);if(c)(c.provides||(c.provides=[])).push(function(){b.result=f.getObject(a);delete b.provides;b.executed!==B&&H(b)});return b.result};i.add("config-publishRequireResult",1,0,0);e.require=function(a,c){var b=function(a,c){var b=u(l(a),g.module);if(v.length&&v[0].finish)v[0].finish.push(a);else{if(b.executed)return b.result;c&&(b.result=A);var h=E();x(b);h=E();b.executed!==B&&b.injected===z&&(k.holdIdle(),I(b),k.releaseIdle());if(b.executed)return b.result;
h==F?b.cjs?C.unshift(b):v.length&&(v[0].finish=[a]):C.push(b)}}(a,c);i("config-publishRequireResult")&&!f.exists(a)&&b!==void 0&&f.setObject(a,b);return b};e.loadInit=function(a){a()};e.registerModulePath=function(a,b){var c={};c[a.replace(/\./g,"/")]=b;g({paths:c})};e.platformRequire=function(a){for(var a=(a.common||[]).concat(a[e._name]||a["default"]||[]),b;a.length;)f.isArray(b=a.shift())?e.require.apply(e,b):e.require(b)};e.requireIf=e.requireAfterIf=function(a,b,c){a&&e.require(b,c)};e.requireLocalization=
function(a,b,c){g(["../i18n"],function(h){h.getLocalization(a,b,c)})};return{extractLegacyApiApplications:q,require:k.dojoRequirePlugin,loadInit:function(b,c,h){c([b],function(b){c(b.names,function(){for(var f="",t=[],q=0;q<arguments.length;q++)f+="var "+b.names[q]+"= arguments["+q+"]; ",t.push(arguments[q]);eval(f);var g=c.module,j=[],f={},k=[],i,q={provide:function(a){a=l(a);a=u(a,g);a!==g&&D(a)},require:function(a,b){a=l(a);b&&(u(a,g).result=A);k.push(a)},requireLocalization:function(a,b,c){j.length||
(j=["dojo/i18n"]);c=(c||e.locale).toLowerCase();a=l(a)+"/nls/"+(/root/i.test(c)?"":c+"/")+l(b);u(a,g).isXd&&j.push("dojo/i18n!"+a)},loadInit:function(a){a()}};try{for(i in q)f[i]=e[i],e[i]=q[i];b.def.apply(null,t)}catch(m){G("error",[{src:d.id,id:"failedDojoLoadInit"},m])}finally{for(i in q)e[i]=f[i]}k.length&&j.push("dojo/require!"+k.join(","));o.push(h);p.forEach(k,function(a){a=u(a,c.module);n.push(a);x(a)});a()})})}}})},"dojo/io/script":function(){define("dojo/io/script",["../main"],function(e){e.getObject("io",
!0,e);var i=e.isIE?"onreadystatechange":"load",g=/complete|loaded/;e.io.script={get:function(d){var j=this._makeScriptDeferred(d),f=j.ioArgs;e._ioAddQueryToUrl(f);e._ioNotifyStart(j);if(this._canAttach(f)){var p=this.attach(f.id,f.url,d.frameDoc);if(!f.jsonp&&!f.args.checkString)var l=e.connect(p,i,function(d){if(d.type=="load"||g.test(p.readyState))e.disconnect(l),f.scriptLoaded=d})}e._ioWatch(j,this._validCheck,this._ioCheck,this._resHandle);return j},attach:function(d,g,f){var f=f||e.doc,i=f.createElement("script");
i.type="text/javascript";i.src=g;i.id=d;i.async=!0;i.charset="utf-8";return f.getElementsByTagName("head")[0].appendChild(i)},remove:function(d,g){e.destroy(e.byId(d,g));this["jsonp_"+d]&&delete this["jsonp_"+d]},_makeScriptDeferred:function(d){var g=e._ioSetArgs(d,this._deferredCancel,this._deferredOk,this._deferredError),f=g.ioArgs;f.id=e._scopeName+"IoScript"+this._counter++;f.canDelete=!1;f.jsonp=d.callbackParamName||d.jsonp;if(f.jsonp)f.query=f.query||"",f.query.length>0&&(f.query+="&"),f.query+=
f.jsonp+"="+(d.frameDoc?"parent.":"")+e._scopeName+".io.script.jsonp_"+f.id+"._jsonpCallback",f.frameDoc=d.frameDoc,f.canDelete=!0,g._jsonpCallback=this._jsonpCallback,this["jsonp_"+f.id]=g;return g},_deferredCancel:function(d){d.canceled=!0;d.ioArgs.canDelete&&e.io.script._addDeadScript(d.ioArgs)},_deferredOk:function(d){d=d.ioArgs;d.canDelete&&e.io.script._addDeadScript(d);return d.json||d.scriptLoaded||d},_deferredError:function(d,g){g.ioArgs.canDelete&&(d.dojoType=="timeout"?e.io.script.remove(g.ioArgs.id,
g.ioArgs.frameDoc):e.io.script._addDeadScript(g.ioArgs));return d},_deadScripts:[],_counter:1,_addDeadScript:function(d){e.io.script._deadScripts.push({id:d.id,frameDoc:d.frameDoc});d.frameDoc=null},_validCheck:function(){var d=e.io.script,g=d._deadScripts;if(g&&g.length>0){for(var f=0;f<g.length;f++)d.remove(g[f].id,g[f].frameDoc),g[f].frameDoc=null;e.io.script._deadScripts=[]}return!0},_ioCheck:function(d){d=d.ioArgs;if(d.json||d.scriptLoaded&&!d.args.checkString)return!0;return(d=d.args.checkString)&&
eval("typeof("+d+") != 'undefined'")},_resHandle:function(d){e.io.script._ioCheck(d)?d.callback(d):d.errback(Error("inconceivable dojo.io.script._resHandle error"))},_canAttach:function(){return!0},_jsonpCallback:function(d){this.ioArgs.json=d}};return e.io.script})},"dojo/_base/browser":function(){require.has&&require.has.add("config-selectorEngine","acme");define("dojo/_base/browser",["../ready","./kernel","./connect","./unload","./window","./event","./html","./NodeList","../query","./xhr","./fx"],
function(e){return e})},"djeo-ge/Placemark":function(){define("djeo-ge/Placemark",["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Color","djeo/_base","djeo/common/Placemark","djeo/util/_base","./_base"],function(e,i,g,d,j,f,p,l){var e=e([f],{constructor:function(a){i.mixin(this,a)},init:function(){this.ge=this.map.engine.ge},render:function(a,c,b){google.earth.executeBatch(this.map.engine.ge,i.hitch(this,function(){this._render(a,c,b)}))},createPlacemark:function(){var a=this.ge.createPlacemark("");
a.setStyleSelector(this.ge.createStyle(""));return a},makePoint:function(a,c){var b=this.createPlacemark(),h=this.ge.createPoint("");h.setLatLngAlt(c[1],c[0],s(a,c));this._setGeometryAttributes(a,h);b.setGeometry(h);return b},makeLineString:function(a,c){var b=this.createPlacemark(),h=this.ge.createLineString("");this._makeLineString(a,h,c);this._setGeometryAttributes(a,h);b.setGeometry(h);return b},_makeLineString:function(a,c,b){g.forEach(b,function(b){c.getCoordinates().pushLatLngAlt(b[1],b[0],
s(a,b))},this)},makePolygon:function(a,c){var b=this.createPlacemark(),h=this.ge.createPolygon("");this._makePolygon(a,h,c);this._setGeometryAttributes(a,h);b.setGeometry(h);return b},_makePolygon:function(a,c,b){g.forEach(b,function(b,d){var f=this.ge.createLinearRing("");g.forEach(b,function(b){f.getCoordinates().pushLatLngAlt(b[1],b[0],s(a,b))});d?c.getInnerBoundaries().appendChild(f):c.setOuterBoundary(f)},this)},makeMultiLineString:function(a,c){var b=this.createPlacemark(),h=this.ge.createMultiGeometry("");
this._setGeometryAttributes(a,h);b.setGeometry(h);g.forEach(c,function(b){var c=this.ge.createLineString("");this._makeLineString(a,c,b);h.getGeometries().appendChild(c)},this);return b},makeMultiPolygon:function(a,c){var b=this.createPlacemark(),h=this.ge.createMultiGeometry("");this._setGeometryAttributes(a,h);b.setGeometry(h);g.forEach(c,function(b){var c=this.ge.createPolygon("");this._makePolygon(a,c,b);h.getGeometries().appendChild(c)},this);return b},_setGeometryAttributes:function(a,c){var b=
j.getTraversedAttr(a,"altitudeMode");l.altitudeModes[b]&&c.setAltitudeMode(this.ge[l.altitudeModes[b]]);b=j.getTraversedAttr(a,"extrude");b!==void 0&&c.setExtrude(b);a.tessellate!=void 0&&c.setTessellate(a.tessellate)},applyPointStyle:function(a,c){var b=c.point,h=f.getSpecificShapeStyle(c.points,this.specificStyleIndex),d=a.baseShapes[0],e=f.get("shape",c,b,h),g=f.getImgSrc(c,b,h),j=!0,m=f.getScale(c,b,h),o=d.getStyleSelector(),d=a.reg.kmlIconScale!==void 0?!0:!1;if(!e&&g)j=!1;else if(!f.shapes[e]&&
!d)e=f.defaultShapeType;o=o.getIconStyle();if(e=j&&e?w+f.shapes[e]:this._getImageUrl(g))g=this.ge.createIcon(""),g.setHref(e),o.setIcon(g);var e=j?f.getSize(c,b,h):f.getImgSize(c,b,h),r;e?(r=j?m*Math.max(e[0],e[1])/l.shapeSize:m,a.reg.kmlIconScale=r):d&&(m=f.get("rScale",c,b,h),m!==void 0&&(r=m*a.reg.kmlIconScale));o.setScale(r);if(!d&&(r=a.orientation,r!==void 0)){if(i.isObject(r))r=r.heading;o.setHeading(p.radToDeg(r))}j&&n(o,c,b,h,!0)},applyLineStyle:function(a,c){var b=c.line,h=f.getSpecificShapeStyle(c.lines,
this.specificStyleIndex),d=a.baseShapes[0].getStyleSelector();m(d,c,b,h);a.extrude&&n(d,c,b,h)},applyPolygonStyle:function(a,c){var b=c.polygon,h=a.baseShapes[0].getStyleSelector();n(h,c,b);m(h,c,b)},remove:function(a){g.forEach(a.baseShapes,function(a){a.getParentNode().getFeatures().removeChild(a)})},show:function(a,c){a.baseShapes[0].setVisibility(c)},makeText:function(a,c){if(a.getCoordsType()=="Point"){var b=f.get("text",c,c.point);if(b){var h=a.baseShapes[0],d=b.label||this._getLabel(a,b);if(d)h.setName(d),
h=h.getStyleSelector().getLabelStyle(),b.fill&&h.getColor().set(o(b.fill,1)),b.geScale&&h.setScale(b.geScale),a.textShapes=!0}}},setCoords:function(a,c){var b=c.baseShapes[0].getGeometry();a.length==3?b.setLatLngAlt(a[1],a[0],a[2]):b.setLatLng(a[1],a[0])},setOrientation:function(a,c){c.baseShapes[0].getStyleSelector().getIconStyle().setHeading(p.radToDeg(a))}}),w=function(a){for(var c=a.match(/\.\.\//g),b=c=c?c.length:0,h=p.baseUrl.length-1;c;)h--,p.baseUrl.charAt(h)=="/"&&c--;return p.baseUrl.substring(0,
h)+"/"+a.substring(3*b)}(f.shapeIconsUrl),o=function(a,c){rgba=(new d(a)).toRgba();rgba[3]=Math.round(255*c);var b=g.map(rgba,function(a){a=a.toString(16);return a.length<2?"0"+a:a});return b[3]+b[2]+b[1]+b[0]},n=function(a,c,b,d,e){var g=f.get("fill",c,b,d),c=f.get("fillOpacity",c,b,d);if(g||c!==void 0)a=e?a:a.getPolyStyle(),a=a.getColor(),g=g?g:[a.getR(),a.getG(),a.getB()],c=c!==void 0?c:a.getA()/255,a.set(o(g,c))},m=function(a,c,b,d){var e=f.get("stroke",c,b,d),g=f.get("strokeWidth",c,b,d),c=f.get("strokeOpacity",
c,b,d);if(e||g!==void 0||c!==void 0)a=a.getLineStyle(),b=a.getColor(),e=e?e:[b.getR(),b.getG(),b.getB()],c=c!==void 0?c:b.getA()/255,b.set(o(e,c)),g!==void 0&&a.setWidth(g)},s=function(a,c){return c.length==3?c[2]:a.height?a.height:0};return e})},"djeo-ge/_base":function(){define("djeo-ge/_base",[],function(){return{shapeSize:50,altitudeModes:{clampToGround:"ALTITUDE_CLAMP_TO_GROUND",relativeToGround:"ALTITUDE_RELATIVE_TO_GROUND",absolute:"ALTITUDE_ABSOLUTE"}}})},"dojo/_base/NodeList":function(){define("dojo/_base/NodeList",
["./kernel","../query","./array","./html","../NodeList-dom"],function(e,i,g){var i=i.NodeList,d=i.prototype;d.connect=i._adaptAsForEach(function(){return e.connect.apply(this,arguments)});d.coords=i._adaptAsMap(e.coords);i.events=["blur","focus","change","click","error","keydown","keypress","keyup","load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","submit"];g.forEach(i.events,function(e){var f="on"+e;d[f]=function(d,e){return this.connect(f,d,e)}});e.NodeList=
i;return e.NodeList})},"djeo-ge/Tooltip":function(){define("djeo-ge/Tooltip",["dojo/_base/declare"],function(e){return e(null,{init:function(){this.ge=this.map.engine.ge;this.balloon=this.ge.createHtmlStringBalloon("")},pointeroverAction:function(e){var g=e.reg.cs,d=this.balloon,g=g.info?g.info(e):this.content(e);d.setContentString(g);d.setFeature(e.baseShapes[0]);this.ge.setBalloon(d)},pointeroutAction:function(){this.ge.setBalloon(null)}})})},"dojo/main":function(){define("dojo/main",["./_base/kernel",
"./has","require","./_base/sniff","./_base/lang","./_base/array","./ready","./_base/declare","./_base/connect","./_base/Deferred","./_base/json","./_base/Color","require","./_base/browser","./_base/loader"],function(e,i,g,d,j,f,p){e.config.isDebug&&g(["./_firebug/firebug"]);var l=e.config.require;l&&(l=f.map(j.isArray(l)?l:[l],function(d){return d.replace(/\./g,"/")}),e.isAsync?g(l):p(1,function(){g(l)}));return e})},"djeo-ge/Engine":function(){define("djeo-ge/Engine",["require","dojo/_base/declare",
"dojo/_base/lang","dojo/_base/array","dojo/aspect","dojo/io/script","dojo/_base/Deferred","dojo/DeferredList","djeo/Engine","./Placemark","djeo/util/_base"],function(e,i,g,d,j,f,p,l,w,o,n){var m={roadmap:1,hybrid:1,terrain:1};globeEvents={click:1,mousemove:1};var s=function(a,c){var b=n.degToRad(a[1]),d=n.degToRad(c[1]),e=n.degToRad(c[1]-a[1]),f=n.degToRad(c[0]-a[0]),b=Math.pow(Math.sin(e/2),2)+Math.cos(b)*Math.cos(d)*Math.pow(Math.sin(f/2),2);return n.earthRadius*2*Math.atan2(Math.sqrt(b),Math.sqrt(1-
b))};return i([w],{type:"ge",canRenderModels:!0,ge:null,constructor:function(){this._require=e;g.mixin(this.ignoredDependencies,{Highlight:1});this._supportedLayers=m;this._initBasicFactories(new o({map:this.map}))},initialize:function(a){window.google?google.load("earth","1",{callback:g.hitch(this,function(){google.earth.createInstance(this.map.container,g.hitch(this,function(c){this.map.projection="EPSG:4326";this.ge=c;this.ge.getOptions().setMouseNavigationEnabled(!1);this.ge.getWindow().setVisibility(!0);
this.initialized=!0;a()}),function(){})})}):this._initializing?j.after(this,"_initializing",g.hitch(this,function(){this.initialize(a)})):(this._initializing=function(){},f.get({url:"https://www.google.com/jsapi",load:g.hitch(this,function(){this._initializing();delete this._initializing;this.initialize(a)})}))},createContainer:function(a){var c=this.ge.createFolder("");this.appendChild(c,a);return c},prepare:function(){this.factories.Placemark.init()},appendChild:function(a,c){c.parent.getContainer().getFeatures().appendChild(a)},
getTopContainer:function(){this.ge.getFeatures();return this.ge},onForFeature:function(a,c,b,d){var e=a.baseShapes[0],b=this.normalizeCallback(a,c,b,d);google.earth.addEventListener(e,c,b);return[e,c,b]},onForMap:function(a,c,b){if(!(a in globeEvents))return{remove:function(){}};var d=this.ge.getGlobe(),e=function(a){c.call(b,{mapCoords:[a.getLongitude(),a.getLatitude()],nativeEvent:a})};google.earth.addEventListener(d,a,e);return{remove:function(){google.earth.removeEventListener(d,a,e)}}},disconnect:function(a){google.earth.removeEventListener(a[0],
a[1],a[2])},zoomTo:function(a){var c=500,b=this.map.width/this.map.height,d=(a[0]+a[2])/2,e=(a[1]+a[3])/2,f=a[3]-a[1];if(a[2]-a[0]||f)c=s([a[2],e],[a[0],e]),a=s([d,a[3]],[d,a[1]]),b=Math.min(Math.max(b,c/a),1),b=n.degToRad(45/(b+0.4)-2),a=Math.max(a,c),a=Math.min(n.degToRad(90),b+a/(2*n.earthRadius)),c=1.5*n.earthRadius*(Math.sin(a)*Math.sqrt(1+1/Math.pow(Math.tan(b),2))-1);b=this.ge.getView().copyAsLookAt(this.ge.ALTITUDE_RELATIVE_TO_GROUND);b.setLongitude(d);b.setLatitude(e);b.setAltitude(0);b.setRange(c);
this.ge.getView().setAbstractView(b)},destroy:function(){},executeBatch:function(a){google.earth.executeBatch(this.ge,a)},enableLayer:function(a,c){var b=this.ge,d=b.getLayerRoot();switch(a.toLowerCase()){case "roadmap":case "hybrid":d.enableLayerById(b.LAYER_BORDERS,c);d.enableLayerById(b.LAYER_ROADS,c);break;case "terrain":d.enableLayerById(b.LAYER_TERRAIN,c)}},renderFeatures:function(){var a=arguments;google.earth.executeBatch(this.ge,g.hitch(this,function(){this.inherited("renderFeatures",a)}))},
renderContainer:function(a,c,b){var d=new p;google.earth.executeBatch(this.ge,g.hitch(this,function(){var e=this._renderContainer(a,c,b);e&&e.length?(new l(e)).then(function(){d.resolve()}):d.resolve()}));return d},_renderContainer:function(a,c,b){if(a.visible){a.features.length==0&&b&&a.parent.numVisibleFeatures++;var e=[];d.forEach(a.features,function(a){if(a.isContainer||a.visible)(a=a._render(c,b))&&(g.isArray(a)?d.forEach(a,function(a){e.push(a)}):e.push(a))});return e.length?e:null}}})})}}});
define("djeo-ge/ge",[],1);