//>>built
require({cache:{"djeo/djeo/Engine":function(){define("djeo/djeo/Engine",["require","dojo/_base/declare","dojo/has","dojo/_base/lang","dojo/_base/array","dojo/dom-construct","dojo/dom-geometry","dojo/on","../_base","../dojox/gfx","../dojox/gfx/matrix","../Engine","./Placemark","../util/geometry","../_tiles"],function(l,p,h,m,j,q,i,f,t,k,n,r,a,c,d){var g={mouseover:"onmouseover",mouseout:"onmouseout",click:"onclick"};return p([r],{scaleFactor:1.2,correctionScale:1E4,pointZoomFactor:0.01,resizePoints:!0,
resizeLines:!0,resizeAreas:!0,correctScale:!1,layers:null,_layerReg:null,container:null,constructor:function(){this._require=l;m.mixin(this.ignoredDependencies,{Highlight:1,Tooltip:1});this._supportedLayers=d;this._initBasicFactories(new a({map:this.map,engine:this}))},initialize:function(e){var b=this.map;this.map.container.style.overflow="hidden";this.container=q.create("div",{style:{width:"100%",height:"100%",position:"relative"}},b.container);this.surface=k.createSurface(this.container,b.width,
b.height);this.surface.rawNode.style.position="absolute";this.group=this.surface.createGroup();if(b.resizePoints!==void 0)this.resizePoints=b.resizePoints;if(b.resizeLines!==void 0)this.resizeLines=b.resizeLines;if(b.resizeAreas!==void 0)this.resizeAreas=b.resizeAreas;if(b.resizePoints!==void 0)this.resizePoints=b.resizePoints;if(b.resizeLines!==void 0)this.resizeLines=b.resizeLines;if(b.resizeAreas!==void 0)this.resizeAreas=b.resizeAreas;this.initialized=!0;e()},createContainer:function(e){return e.createGroup()},
prepare:function(){var e=this.map.getBbox();if(e)this.extent=e;var b=e[3]-e[1];if(e[2]-e[0]<1E3||b<1E3)this.correctScale=!0;this.factories.Placemark.init();this.factories.Placemark.prepare()},getTopContainer:function(){return this.group},onForFeature:function(e,b,a,c){var d=[],a=this.normalizeCallback(e,b,a,c),b=g[b];j.forEach(e.baseShapes,function(e){d.push([e,e.connect(b,a)])});return d},disconnect:function(e){j.forEach(e,function(b){b[0].disconnect(b[1])})},destroy:function(){this.surface.destroy()},
onForMap:function(e,b,a){return f(this.map.container,e,m.hitch(this,function(e){var c=i.position(this.container,!0),c=this.map.containerPixelToCoords(e.pageX-c.x,e.pageY-c.y);b.call(a,{mapCoords:c,nativeEvent:e})}))},_on_zoom_changed:function(e,b,a){return f(this,e,m.hitch(a,b))},_on_extent_changed:function(e,b,a){return f(this,e,m.hitch(a,b))},zoomTo:function(e){var b=this.map,a=e[2]-e[0],c=e[3]-e[1],d=(this.group.getTransform()||{xx:1}).xx,g=Math.min(b.width/a,b.height/c),f=this.factories.Placemark,
i=f.getX(e[0]),h=f.getY(e[3]);a==0&&c==0&&(a=b.extent||b.getBbox(),g=this.pointZoomFactor*Math.min(a[2]-a[0],a[3]-a[1]),b.width>b.height?(c=g,a=b.width/b.height*g):(a=g,c=b.height/b.width*g),g=b.width/a,i=f.getX(e[0]-a/2),h=f.getY(e[3]+c/2));var k=this.layers;k.length&&(j.forEach(k,function(a){a.zoomTo(e)}),k[0].discreteScales&&(g=k[0].getScale()));k=g;this.correctScale&&(g/=this.correctionScale);this.group.setTransform([n.translate((b.width-k*a)/2,(b.height-k*c)/2),n.scale(g),n.translate(-i,-h)]);
d!=g&&(f.calculateLengthDenominator(),this.resizeFeatures(this.map.document,d/g));this.onzoom_changed()},resizeFeatures:function(a,b){j.forEach(a.features,function(a){a.isPlacemark?this._resizePlacemark(a,b):a.isContainer&&this.resizeFeatures(a,b)},this)},_resizePlacemark:function(a,b){if(!a.invalid&&(this.resizePoints&&a.isPoint()?j.forEach(a.baseShapes,function(a){a.applyRightTransform(n.scale(b))}):k.renderer!="vml"&&!(k.renderer=="svg"&&(h("webkit")||h("opera")))&&(this.resizeLines&&a.isLine()||
this.resizeAreas&&a.isArea())&&j.forEach(a.baseShapes,function(a){var e=a.getStroke();e&&(e.width*=b,a.setStroke(e))}),a.textShapes)){var c=this.map.engine.factories.Placemark._calculateTextPosition(a);j.forEach(a.textShapes,function(a){a.setTransform(c)})}},_setCamera:function(a){var b=this.map,c=b.engine.factories.Placemark,d=t.scales[a.zoom],g=c.getX(a.center[0]-b.width/d/2),f=c.getY(a.center[1]+b.height/d/2),k=this.layers;k.length&&j.forEach(k,function(b){b._setCenterAndZoom(a.center,a.zoom)},
this);this.correctScale&&(d/=this.correctionScale);this.group.setTransform([n.scale(d),n.translate(-g,-f)]);c.calculateLengthDenominator();this.resizeFeatures(b.document,1/d)},_set_center:function(a){var a=this.map.getCoords(a),b=this.map,c=b.engine.factories.Placemark,d=(this.group.getTransform()||{xx:1}).xx,g=d,f=this.layers;f.length&&j.forEach(f,function(b){b.setCenter(a)},this);this.correctScale&&(g*=this.correctionScale);f=c.getX(a[0]-b.width/g/2);b=c.getY(a[1]+b.height/g/2);this.group.setTransform([n.scale(d),
n.translate(-f,-b)])},_get_center:function(){var a=this.map;return this.containerPixelToCoords(a.width/2,a.height/2)},_set_zoom:function(a){var b=this.map;if(!(a<b.minZoom||a>b.maxZoom)){var c=(this.group.getTransform()||{xx:1}).xx,c=t.scales[a]/c,d=this.layers;d.length&&j.forEach(d,function(b){b.setZoom(a)});this.group.applyLeftTransform({xx:c,yy:c,dx:b.width/2*(1-c),dy:b.height/2*(1-c)});this.factories.Placemark.calculateLengthDenominator();this.resizeFeatures(this.map.document,1/c);this.onzoom_changed()}},
_get_zoom:function(){return this.layers.length?this.layers[0].zoom:-1},_get_extent:function(){var a=this.map,b=this.containerPixelToCoords(0,a.height),a=this.containerPixelToCoords(a.width,0);return[b[0],b[1],a[0],a[1]]},containerPixelToCoords:function(a,b){var c=this.group.getTransform(),d=c.xx,g=-c.dx/d,c=-c.dy/d;this.correctScale&&(g/=this.correctionScale,c/=this.correctionScale);this.correctScale&&(d*=this.correctionScale);g+=this.extent[0]+a/d;c=this.extent[3]-c-b/d;return[g,c]},_appendDiv:function(a){this.container.children[0].appendChild(a)}})})},
"djeo/util/geometry":function(){define("djeo/util/geometry",["./bbox"],function(l){return{center:function(p){var p=l.get(p),h;p&&(h=[(p[0]+p[2])/2,(p[1]+p[3])/2]);return h}}})},"djeo/djeo/Moveable":function(){define("djeo/djeo/Moveable",["dojo/_base/declare","dojo/_base/event","dojo/on","dojo/touch","dojo/_base/lang","dojo/dom-class","./Mover"],function(l,p,h,m,j,q,i){return l(null,{delay:0,constructor:function(f,t){this.node=f;this.map=t;this.mover=i;this._pressHandle=h(f,m.press,j.hitch(this,this.onPress))},
destroy:function(){this._pressHandle.remove();delete this._pressHandle},onPress:function(f){if(this.delay)this._onMoveHandle=h(this.node,m.move,j.hitch(this,this._onMove)),this._onReleaseHandle=h(this.node,m.release,j.hitch(this,this.onRelease)),this._lastX=f.pageX,this._lastY=f.pageY;else this.onDragDetected(f);p.stop(f)},_onMove:function(f){if(Math.abs(f.pageX-this._lastX)>this.delay||Math.abs(f.pageY-this._lastY)>this.delay)this.onRelease(f),this.onDragDetected(f);p.stop(f)},onRelease:function(f){this._onReleaseHandle.cancel();
this._onMoveHandle.cancel();delete this._onReleaseHandle;p.stop(f)},onDragDetected:function(f){new this.mover(this.node,f,this)},onMoveStart:function(){},onMoveStop:function(){},onFirstMove:function(){for(var f=this.map.engine,i=0;i<f.layers.length;i++)f.layers[i].setStartPos()},onMove:function(f,i,k,n,h){this.onMoving(f,i,k,n,h);var a=this.map.engine;a.group.applyLeftTransform({dx:n,dy:h});if(a._infoWindow){s=a._infoWindow.domNode.style;var c=s.left,d=s.top;s.left=c?parseInt(c.substr(0,c.length-
2))+n:n;s.top=d?parseInt(d.substr(0,d.length-2))+h:h}for(c=0;c<a.layers.length;c++)a.layers[c].onMove(i,k);this.onMoved(f,i,k,n,h)},onMoving:function(){},onMoved:function(){}})})},"djeo/djeo/Mover":function(){define("djeo/djeo/Mover",["dojo/_base/declare","dojo/has","dojo/_base/event","dojo/on","dojo/touch","dojo/_base/lang","dojo/_base/sniff"],function(l,p,h,m,j,q){return l(null,{constructor:function(i,f,h){this.node=i;this.startX=f.touches?f.touches[0].pageX:f.pageX;this.startY=f.touches?f.touches[0].pageY:
f.pageY;this.mouseButton=f.button;f=this.host=h;i=i.ownerDocument;this._onFirstMove=m(i,j.move,q.hitch(this,this.onFirstMove));this._onMouseMove=m(i,j.move,q.hitch(this,this.onMouseMove));this._onMouseUp=m(i,j.release,q.hitch(this,this.onMouseUp));if(f&&f.onMoveStart)f.onMoveStart(this)},onMouseMove:function(i){var f=i.touches?i.touches[0].pageX:i.pageX,j=i.touches?i.touches[0].pageY:i.pageY;this.host.onMove(this,this.startPosX+(f-this.startX),this.startPosY+(j-this.startY),f-this.lastX,j-this.lastY,
i);this.lastX=f;this.lastY=j;h.stop(i)},onMouseUp:function(i){(p("webkit")&&p("mac")&&this.mouseButton==2?i.button==0:this.mouseButton==i.button)&&this.destroy();h.stop(i)},onFirstMove:function(i){var f=this.node.style,h=this.host;this.startPosX=Math.round(parseFloat(f.left))||0;this.startPosY=Math.round(parseFloat(f.top))||0;this.lastX=this.startX;this.lastY=this.startY;if(h&&h.onFirstMove)h.onFirstMove(this,i);this._onFirstMove.remove();delete this._onFirstMove},destroy:function(){this._onFirstMove&&
this._onFirstMove.remove();this._onMouseUp.remove();this._onMouseMove.remove();var h=this.host;if(h&&h.onMoveStop)h.onMoveStop(this);this._onFirstMove=this._onMouseMove=this._onMouseUp=this._onFirstMove=this.node=this.host=null}})})},"djeo/djeo/Placemark":function(){define("djeo/djeo/Placemark",["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/has","../dojox/gfx","../dojox/gfx/matrix","../_base","../common/Placemark","../util/geometry","../gfx"],function(l,p,h,m,j,q,i,f,t,k){var n=
function(a){j.renderer=="svg"&&!m("mozilla")&&a.rawNode.setAttribute("vector-effect","non-scaling-stroke");return a},r={family:1,size:1,weight:1,style:1,variant:1};return l([f],{multipleSymbolizers:!0,constructor:function(a){p.mixin(this,a)},init:function(){this.group=this.engine.group;this.areas=this.group.createGroup();this.lines=this.group.createGroup();this.points=this.group.createGroup();this.text=this.group.createGroup()},prepare:function(){this.calculateLengthDenominator()},calculateLengthDenominator:function(){this.lengthDenominator=
(this.group.getTransform()||{xx:1}).xx},getX:function(a){a-=this.engine.extent[0];this.engine.correctScale&&(a*=this.engine.correctionScale);return parseInt(a)},getY:function(a){a=this.engine.extent[3]-a;this.engine.correctScale&&(a*=this.engine.correctionScale);return parseInt(a)},makePoint:function(){return null},makeLineString:function(a,c){return n(this.lines.createPath({path:this.makePathString(c,1)}))},makePolygon:function(a,c){return n(this.areas.createPath({path:this.makePathString(c,2)}))},
makeMultiLineString:function(a,c){return n(this.lines.createPath({path:this.makePathString(c,2)}))},makeMultiPolygon:function(a,c){return n(this.areas.createPath({path:this.makePathString(c,3)}))},applyPointStyle:function(a,c,d){var g=c.point,e=c.points,b=a.baseShapes,f=b.length;if(e){this._updateShapes(a,d,c,e,!0);var i=!1;h.forEach(e,function(e,h){var k=b[h];k&&i&&(this._removeShape(k,a),k=null);var n=this._applyPointStyle(d,c,g,e,a,k);k&&k!=n&&(i=!0,b[h]=n);h>=f&&b.push(n)},this)}else if(f>1)h.forEach(b,
function(b,e){var h=this._applyPointStyle(d,c,g,null,a,b);if(f==0||h!=b)a.baseShapes[e]=h},this);else{var e=b[0],k=this._applyPointStyle(d,c,g,null,a,e);if(f==0||e!=k)a.baseShapes[0]=k}},_applyPointStyle:function(a,c,d,g,e,b){var h=f.get("shape",c,d,g),j=f.getImgSrc(c,d,g),l,o,m,r=f.getScale(c,d,g),a=[q.translate(this.getX(a[0]),this.getY(a[1]))],t=!0,u=!b?!0:!1;if(h){if(!i.shapes[h])h=f.defaultShapeType;l=!0}else j&&(l=!1);l!==void 0&&(o=l?f.getSize(c,d,g):f.getImgSize(c,d,g));if(o)e.reg.size=[o[0],
o[1]],e.reg.scale=r;else if(b&&(m=f.get("rScale",c,d,g),l!==void 0&&m!==void 0))o=e.reg.size,r=m*e.reg.scale;l?(l=i.shapes[h],j=h=="circle"?2:Math.max(l.size[0],l.size[1]),m=r/this.lengthDenominator/j,a.push(q.scale(m*o[0],m*o[1])),h=="circle"?(b&&b.shape.type!="circle"&&(this._removeShape(b,e),u=!0,b=null),h={cx:0,cy:0,r:1},b?b.setShape(h):b=n(this.points.createCircle(h))):(b&&b.shape.type!="polyline"&&(this._removeShape(b,e),u=!0,b=null),b?b.setShape({points:l.points}):b=n(this.points.createPolyline(l.points))),
k.applyFill(b,c,d,g),k.applyStroke(b,c,d,g,j/Math.max(o[0],o[1])/r)):l===!1?(b&&b.shape.type!="image"&&(this._removeShape(b,e),u=!0,b=null),c=f.getAnchor(c,d,g,o),o={type:"image",src:this._getImageUrl(j),width:o[0],height:o[1],x:-c[0],y:-c[1]},b?b.setShape(o):b=this.points.createImage(o),a.push(q.scale(1/this.lengthDenominator*r))):b&&(b.shape.type!="image"&&k.applyFill(b,c,d,g),m!==void 0&&(b.applyRightTransform(q.scale(c.rScale)),t=!1));if(b){if(t){r=e.reg;o=r.heading;if(o===void 0){o=e.orientation;
if(p.isObject(o))o=o.heading;r.heading=o}o!==void 0&&a.push(q.rotate(o));b.setTransform(a)}u&&this._connectEvents(b,e)}return b},applyLineStyle:function(a,c,d){var g=c.line,e=c.lines,b=a.baseShapes;e?(this._updateShapes(a,d,c,e),h.forEach(e,function(a,d){this._applyLineStyle(b[d],c,g,a)},this)):h.forEach(b,function(a){this._applyLineStyle(a,c,g)},this)},_applyLineStyle:function(a,c,d,g){k.applyStroke(a,c,d,g,1/this.lengthDenominator)},applyPolygonStyle:function(a,c,d){this._updateShapes(a,d,c);this._applyPolygonStyle(a.baseShapes[0],
c,c.area)},_applyPolygonStyle:function(a,c,d){k.applyFill(a,c,d);k.applyStroke(a,c,d,null,1/this.lengthDenominator)},_updateShapes:function(a,c,d,g,e){var d=a.baseShapes,g=g?g.length:1,b=d.length;if(g>b){if(!e)for(e=b;e<g;e++)b=this.createShape(a,c),this._connectEvents(b,a),d.push(b)}else if(g<b)for(e=b-1;e>=g;e--)b=d.pop(),this._removeShape(b,a)},_connectEvents:function(a,c){var d=c.handles,g;for(g in d){var e=d[g][1],b=d[g][2],f=d[g][3];h.forEach(d[g][0],function(d,g){f[g].push([a,a.connect(d,this.engine.normalizeCallback(c,
d,b,e))])},this)}},_removeShape:function(a,c){var d=c.handles;a.removeShape();for(var g in d){var e=d[g][3];h.forEach(d[g][0],function(b,c){a.disconnect(e[c].pop()[1])})}},remove:function(a){a.visible&&h.forEach(a.baseShapes,function(c){this._removeShape(c,a)},this)},show:function(a,c){if(c){var d=a.reg.gfxContainer;delete a.reg.gfxContainer;h.forEach(a.baseShapes,function(a){d.add(a)},this)}else{if(a.baseShapes.length)a.reg.gfxContainer=a.baseShapes[0].getParent();h.forEach(a.baseShapes,function(a){a.removeShape()})}},
makeText:function(a,c){if(j.renderer!="vml"){a.textShapes&&h.forEach(a.textShapes,function(a){a.removeShape()});var d;if(a.isPoint())d=c.point;else if(a.isArea())d=c.area;if(d=f.get("text",c,d)){var g=d.label||this._getLabel(a,d);if(g)a.textShapes=[],a.reg.ts=d,d.haloFill&&d.haloRadius&&this._makeTextShape(a,g,null,{color:d.haloFill,width:2*d.haloRadius},d),this._makeTextShape(a,g,d.fill,null,d)}}},_makeTextShape:function(a,c,d,g,e){var b={},h=!0;if(a.isPoint()){if(e.hAlign)b.align=e.hAlign}else a.isArea()?
b.align="middle":h=!1;if(h)b.text=c,c=this._calculateTextPosition(a,b),b=this.text.createText(b).setTransform(c),d&&b.setFill(d),this._makeFont(b,e,f.getScale(a.reg.cs)),g&&b.setStroke(g),a.textShapes.push(b)},_calculateTextPosition:function(a,c,d){var g;g===void 0?d||(d=a.getCoords()):d=t.center(a);g=this.getX(d[0]);var d=this.getY(d[1]),e=a.reg.ts,b=f.getScale(a.reg.cs),a=[q.scaleAt(1/this.lengthDenominator,g,d)],h="dx"in e?b*e.dx:0,e="dy"in e?-b*e.dy:0;(h||e)&&a.push(q.translate(h,e));if(c)c.x=
g,c.y=d;return a},_makeFont:function(a,c,d){var g,e;for(e in r)e in c&&(g||(g={}),g[e]=c[e]);g&&(g.size&&(g.size*=d),a.setFont(g))},setCoords:function(a,c){var d=c.baseShapes,g=c.textShapes,e=c.getCoords(),b={dx:this.getX(a[0])-this.getX(e[0]),dy:this.getY(a[1])-this.getY(e[1])};h.forEach(d,function(a){a.applyLeftTransform(b)},this);g&&h.forEach(g,function(b){var d=b.getShape(),e=this._calculateTextPosition(c,d,a);b.setShape(d).setTransform(e)},this)},setOrientation:function(a,c){var d=c.reg;if(d.heading===
void 0)d.heading=0;var g=-d.heading+a;h.forEach(c.baseShapes,function(a){a.applyRightTransform(q.rotate(g))},this);d.heading=a},makePathString:function(a,c){var d="";if(c==1)for(var d="M"+this.getX(a[0][0])+","+this.getY(a[0][1]),g=1;g<a.length;g++)d+="L"+this.getX(a[g][0])+","+this.getY(a[g][1]);else h.forEach(a,function(a){d+=this.makePathString(a,c-1)},this);return d}})})},"djeo/djeo/Navigation":function(){define("djeo/djeo/Navigation",["dojo/_base/declare","dojo/has","dojo/on","dojo/aspect","dojo/_base/lang",
"dojo/_base/event","dojo/dom-geometry","../dojox/gfx","./Moveable","dojo/_base/sniff"],function(l,p,h,m,j,q,i,f,t){return l(null,{moveable:null,enable:function(h){h===void 0&&(h=!0);h?(this.moveable=new t(this.map.engine.container,this.map),this._onFirstMove=m.after(this.moveable,"onFirstMove",j.hitch(this,function(){this._moved=!0})),this._onMoveStop=m.after(this.moveable,"onMoveStop",j.hitch(this,function(){if(this._moved)this._moved=!1,this.map.engine.emit("extent_changed")})),f.renderer!="silverlight"&&
this.enableZoom(!0)):(f.renderer!="silverlight"&&this.enableZoom(!1),this._onMoveStop.remove(),this._onFirstMove.remove(),this.moveable.destroy(),this.moveable=null)},enableZoom:function(f){if(f){var i=this.map.engine,f=!p("mozilla")?"mousewheel":"DOMMouseScroll";this.wheelHandler=h(i.container,f,j.hitch(this,this._onWheel));this.dblclickHandler=h(i.container,"dblclick",j.hitch(this,function(f){this._onZoom(f,i.scaleFactor)}))}else this.dblclickHandler.remove(),this.wheelHandler.remove(),this.wheelHandler=
this.dblclickHandler=null},_onWheel:function(f){var h=f[p("mozilla")?"detail":"wheelDelta"]/(p("mozilla")?-3:120);this._onZoom(f,Math.pow(this.map.engine.scaleFactor,h))},_onZoom:function(f,h){q.stop(f);var j=this.map,a=j.engine,c=a._get_zoom();if(!(c>=0&&(c==j.minZoom&&h<1||c==j.maxZoom&&h>1))){for(var c=i.position(this.map.engine.container,!0),j=f.pageX-c.x,c=f.pageY-c.y,d=0;d<a.layers.length;d++)a.layers[d].doZoom(h,f);a.group.applyLeftTransform({xx:h,yy:h,dx:j*(1-h),dy:c*(1-h)});a.factories.Placemark.calculateLengthDenominator();
a.resizeFeatures(this.map.document,1/h);a._infoWindow&&a._infoWindow._doZoom(h,j,c);a.onzoom_changed();a.emit("extent_changed")}}})})},"djeo/_tiles":function(){define("djeo/_tiles",[],function(){var l=["WebTiles",{url:"http://[a,b,c].tile.openstreetmap.org"}];return{webtiles:["WebTiles",{}],roadmap:l,osm:l,openstreetmap:l,"osm.org":l,"openstreetmap.org":l,"mapquest-osm":["WebTiles",{url:"http://otile[1,2,3,4].mqcdn.com/tiles/1.0.0/osm"}],"mapquest-oa":["WebTiles",{url:"http://oatile[1,2,3,4].mqcdn.com/tiles/1.0.0/sat"}],
arcgis_webtiles:["WebTiles",{}]}})}}});define("djeo/native",[],1);