//>>built
require({cache:{"dojo/NodeList-dom":function(){define("dojo/NodeList-dom",["./_base/kernel","./query","./_base/array","./_base/lang","./dom-class","./dom-construct","./dom-geometry","./dom-attr","./dom-style"],function(b,k,e,c,l,d,m,n,o){function r(b){return function(a,c,d){if(arguments.length==2)return b[typeof c=="string"?"get":"set"](a,c);return b.set(a,c,d)}}var g=function(b){return b.length==1&&typeof b[0]=="string"},f=function(b){var c=b.parentNode;c&&c.removeChild(b)},j=k.NodeList,a=j._adaptWithCondition,
h=j._adaptAsForEach,t=j._adaptAsMap;c.extend(j,{_normalize:function(a,f){var g=a.parse===!0;if(typeof a.template=="string")var h=a.templateFunc||b.string&&b.string.substitute,a=h?h(a.template,a):a;h=typeof a;h=="string"||h=="number"?(a=d.toDom(a,f&&f.ownerDocument),a=a.nodeType==11?c._toArray(a.childNodes):[a]):c.isArrayLike(a)?c.isArray(a)||(a=c._toArray(a)):a=[a];if(g)a._runParse=!0;return a},_cloneNode:function(a){return a.cloneNode(!0)},_place:function(a,c,f,h){if(!(c.nodeType!=1&&f=="only"))for(var g,
r=a.length,j=r-1;j>=0;j--){var l=h?this._cloneNode(a[j]):a[j];if(a._runParse&&b.parser&&b.parser.parse){g||(g=c.ownerDocument.createElement("div"));g.appendChild(l);b.parser.parse(g);for(l=g.firstChild;g.firstChild;)g.removeChild(g.firstChild)}j==r-1?d.place(l,c,f):c.parentNode.insertBefore(l,c);c=l}},attr:a(r(n),g),style:a(r(o),g),addClass:h(l.add),removeClass:h(l.remove),replaceClass:h(l.replace),toggleClass:h(l.toggle),empty:h(d.empty),removeAttr:h(n.remove),position:t(m.position),marginBox:t(m.getMarginBox),
place:function(a,c){var b=k(a)[0];return this.forEach(function(a){d.place(a,b,c)})},orphan:function(a){return(a?k._filterResult(this,a):this).forEach(f)},adopt:function(a,c){return k(a).place(this[0],c)._stash(this)},query:function(a){if(!a)return this;var c=new j;this.map(function(b){k(a,b).forEach(function(a){a!==void 0&&c.push(a)})});return c._stash(this)},filter:function(a){var c=arguments,b=this,g=0;if(typeof a=="string"){b=k._filterResult(this,c[0]);if(c.length==1)return b._stash(this);g=1}return this._wrap(e.filter(b,
c[g],c[g+1]),this)},addContent:function(a,c){for(var a=this._normalize(a,this[0]),b=0,g;g=this[b];b++)this._place(a,g,c,b>0);return this}});return j})},"dojo/_base/loader":function(){define("dojo/_base/loader",["./kernel","../has","require","module","./json","./lang","./array"],function(b,k,e,c,l,d,m){var n=function(a){return a.replace(/\./g,"/")},o=/\/\/>>built/,r=[],g=[],f,j=function(a){f[a.mid]=1;for(var c,b,g=a.deps||[],d=0;d<g.length;d++)if(b=g[d],!(c=f[b.mid]))if(c===0||!j(b))return f[a.mid]=
0,!1;return!0},a=function(){var a,c;f={};for(c in A)if(a=A[c],a.executed||a.noReqPluginCheck)f[c]=1;else{if(a.noReqPluginCheck!==0)a.noReqPluginCheck=/loadInit\!/.test(c)||/require\!/.test(c)?1:0;a.noReqPluginCheck?f[c]=1:a.injected!==s&&(f[c]=0)}for(var b=0,d=g.length;b<d;b++)if(a=g[b],!(c=f[a.mid]))if(c===0||!j(a))return;i.holdIdle();a=r;r=[];m.forEach(a,function(a){a(1)});i.releaseIdle()},h=function(a,c,g){var d=/\(|\)/g,f=1;for(d.lastIndex=c;c=d.exec(a);)if(c[0]==")"?f-=1:f+=1,f==0)break;if(f!=
0)throw"unmatched paren around character "+d.lastIndex+" in: "+a;return[b.trim(a.substring(g,d.lastIndex))+";\n",d.lastIndex]},t=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,p=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,x=/(^|\s)(require|define)\s*\(/m,w=function(a,c){var b,g,d,f=[],j=[];b=[];for(c=c||a.replace(t,function(a){p.lastIndex=x.lastIndex=0;return p.test(a)||x.test(a)?"":a});b=p.exec(c);)g=p.lastIndex,d=g-b[0].length,g=h(c,g,d),b[2]==
"loadInit"?f.push(g[0]):j.push(g[0]),p.lastIndex=g[1];b=f.concat(j);return b.length||!x.test(c)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 && dojo.loadInit("),b.join(""),b]:0},i=e.initSyncLoader(function(c,b,d){r.push(d);m.forEach(c.split(","),function(a){a=u(a,b.module);g.push(a);z(a)});a()},a,function(a,c){var g,d,f=[],h=[];if(o.test(c)||!(g=w(c)))return 0;d=a.mid+"-*loadInit";for(var j in u("dojo",a).result.scopeMap)f.push(j),h.push('"'+j+'"');return"// xdomain rewrite of "+a.path+"\ndefine('"+
d+"',{\n\tnames:"+b.toJson(f)+",\n\tdef:function("+f.join(",")+"){"+g[1]+"}});\n\ndefine("+b.toJson(f.concat(["dojo/loadInit!"+d]))+", function("+f.join(",")+"){\n"+g[0]+"});"}),y=i.sync,s=i.arrived,q=i.nonmodule,F=i.executing,B=i.executed,v=i.syncExecStack,A=i.modules,C=i.execQ,u=i.getModule,z=i.injectModule,D=i.setArrived,G=i.signal,H=i.finishExec,I=i.execModule,E=i.getLegacyMode;b.provide=function(a){var c=v[0],b=d.mixin(u(n(a),e.module),{executed:F,result:d.getObject(a,!0)});D(b);if(c)(c.provides||
(c.provides=[])).push(function(){b.result=d.getObject(a);delete b.provides;b.executed!==B&&H(b)});return b.result};k.add("config-publishRequireResult",1,0,0);b.require=function(a,c){var b=function(a,c){var b=u(n(a),e.module);if(v.length&&v[0].finish)v[0].finish.push(a);else{if(b.executed)return b.result;c&&(b.result=q);var g=E();z(b);g=E();b.executed!==B&&b.injected===s&&(i.holdIdle(),I(b),i.releaseIdle());if(b.executed)return b.result;g==y?b.cjs?C.unshift(b):v.length&&(v[0].finish=[a]):C.push(b)}}(a,
c);k("config-publishRequireResult")&&!d.exists(a)&&b!==void 0&&d.setObject(a,b);return b};b.loadInit=function(a){a()};b.registerModulePath=function(a,b){var c={};c[a.replace(/\./g,"/")]=b;e({paths:c})};b.platformRequire=function(a){for(var a=(a.common||[]).concat(a[b._name]||a["default"]||[]),c;a.length;)d.isArray(c=a.shift())?b.require.apply(b,c):b.require(c)};b.requireIf=b.requireAfterIf=function(a,c,g){a&&b.require(c,g)};b.requireLocalization=function(a,c,b){e(["../i18n"],function(g){g.getLocalization(a,
c,b)})};return{extractLegacyApiApplications:w,require:i.dojoRequirePlugin,loadInit:function(d,f,h){f([d],function(d){f(d.names,function(){for(var j="",l=[],e=0;e<arguments.length;e++)j+="var "+d.names[e]+"= arguments["+e+"]; ",l.push(arguments[e]);eval(j);var i=f.module,k=[],j={},t=[],p,e={provide:function(a){a=n(a);a=u(a,i);a!==i&&D(a)},require:function(a,c){a=n(a);c&&(u(a,i).result=q);t.push(a)},requireLocalization:function(a,c,g){k.length||(k=["dojo/i18n"]);g=(g||b.locale).toLowerCase();a=n(a)+
"/nls/"+(/root/i.test(g)?"":g+"/")+n(c);u(a,i).isXd&&k.push("dojo/i18n!"+a)},loadInit:function(a){a()}};try{for(p in e)j[p]=b[p],b[p]=e[p];d.def.apply(null,l)}catch(o){G("error",[{src:c.id,id:"failedDojoLoadInit"},o])}finally{for(p in e)b[p]=j[p]}t.length&&k.push("dojo/require!"+t.join(","));r.push(h);m.forEach(t,function(a){a=u(a,f.module);g.push(a);z(a)});a()})})}}})},"dojo/io/script":function(){define("dojo/io/script",["../main"],function(b){b.getObject("io",!0,b);var k=b.isIE?"onreadystatechange":
"load",e=/complete|loaded/;b.io.script={get:function(c){var l=this._makeScriptDeferred(c),d=l.ioArgs;b._ioAddQueryToUrl(d);b._ioNotifyStart(l);if(this._canAttach(d)){var m=this.attach(d.id,d.url,c.frameDoc);if(!d.jsonp&&!d.args.checkString)var n=b.connect(m,k,function(c){if(c.type=="load"||e.test(m.readyState))b.disconnect(n),d.scriptLoaded=c})}b._ioWatch(l,this._validCheck,this._ioCheck,this._resHandle);return l},attach:function(c,l,d){var d=d||b.doc,e=d.createElement("script");e.type="text/javascript";
e.src=l;e.id=c;e.async=!0;e.charset="utf-8";return d.getElementsByTagName("head")[0].appendChild(e)},remove:function(c,e){b.destroy(b.byId(c,e));this["jsonp_"+c]&&delete this["jsonp_"+c]},_makeScriptDeferred:function(c){var e=b._ioSetArgs(c,this._deferredCancel,this._deferredOk,this._deferredError),d=e.ioArgs;d.id=b._scopeName+"IoScript"+this._counter++;d.canDelete=!1;d.jsonp=c.callbackParamName||c.jsonp;if(d.jsonp)d.query=d.query||"",d.query.length>0&&(d.query+="&"),d.query+=d.jsonp+"="+(c.frameDoc?
"parent.":"")+b._scopeName+".io.script.jsonp_"+d.id+"._jsonpCallback",d.frameDoc=c.frameDoc,d.canDelete=!0,e._jsonpCallback=this._jsonpCallback,this["jsonp_"+d.id]=e;return e},_deferredCancel:function(c){c.canceled=!0;c.ioArgs.canDelete&&b.io.script._addDeadScript(c.ioArgs)},_deferredOk:function(c){c=c.ioArgs;c.canDelete&&b.io.script._addDeadScript(c);return c.json||c.scriptLoaded||c},_deferredError:function(c,e){e.ioArgs.canDelete&&(c.dojoType=="timeout"?b.io.script.remove(e.ioArgs.id,e.ioArgs.frameDoc):
b.io.script._addDeadScript(e.ioArgs));return c},_deadScripts:[],_counter:1,_addDeadScript:function(c){b.io.script._deadScripts.push({id:c.id,frameDoc:c.frameDoc});c.frameDoc=null},_validCheck:function(){var c=b.io.script,e=c._deadScripts;if(e&&e.length>0){for(var d=0;d<e.length;d++)c.remove(e[d].id,e[d].frameDoc),e[d].frameDoc=null;b.io.script._deadScripts=[]}return!0},_ioCheck:function(c){c=c.ioArgs;if(c.json||c.scriptLoaded&&!c.args.checkString)return!0;return(c=c.args.checkString)&&eval("typeof("+
c+") != 'undefined'")},_resHandle:function(c){b.io.script._ioCheck(c)?c.callback(c):c.errback(Error("inconceivable dojo.io.script._resHandle error"))},_canAttach:function(){return!0},_jsonpCallback:function(c){this.ioArgs.json=c}};return b.io.script})},"dojo/_base/browser":function(){require.has&&require.has.add("config-selectorEngine","acme");define("dojo/_base/browser",["../ready","./kernel","./connect","./unload","./window","./event","./html","./NodeList","../query","./xhr","./fx"],function(b){return b})},
"djeo-ymaps/Engine":function(){define("djeo-ymaps/Engine",["require","dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/aspect","dojo/io/script","djeo/Engine","./Placemark","djeo/_tiles"],function(b,k,e,c,l,d,m,n,o){function r(a,c,b,g){return{remove:function(){a.events.remove(c,b,g)}}}var g=window.ymaps,f={roadmap:"map",satellite:"satellite",hybrid:"hybrid"},j={click:"click",mouseover:"mouseenter",mouseout:"mouseleave"},o=e.mixin(e.mixin({},o),f);return k([m],{ymap:null,constructor:function(){this._require=
b;e.mixin(this.ignoredDependencies,{Highlight:1,Tooltip:1});this._supportedLayers=o;this._initBasicFactories(new n({map:this.map,engine:this}))},initialize:function(a){if(g){var c=this.map;c.projection="EPSG:4326";c=new g.Map(c.container,{minZoom:c.minZoom,maxZoom:c.maxZoom,propagateEvents:!0,center:[0,0],zoom:0,type:null});c.behaviors.disable(["drag","dblClickZoom"]);this.ymap=c;this.initialized=!0;a()}else if(this._initializing)l.after(this,"_initializing",e.hitch(this,function(){this.initialize(a)}));
else{this._initializing=function(){};var c={coordorder:"longlat",load:"package.full",lang:"ru-RU"},f=this.map.ymapsKey||b.rawConfig.ymapsKey;if(f)c.key=f;d.get({url:"http://api-maps.yandex.ru/2.0/",content:c,load:e.hitch(this,function(){ymaps.ready(e.hitch(this,function(){n.init();g=ymaps;this._initializing();delete this._initializing;this.initialize(a)}))})})}},createContainer:function(){},appendChild:function(a){this.ymap.geoObjects.add(a)},onForFeature:function(a,c,b,g){b=this.normalizeCallback(a,
c,b,g);a=a.baseShapes[0];a.events.add(j[c],b,g);return[[a,j[c],b,g]]},disconnect:function(a){c.forEach(a,function(a){a[0].events.remove(a[1],a[2],a[3])})},onForMap:function(a,c,b){var g=function(a){c.call(b,{mapCoords:a.get("coordPosition"),nativeEvent:a})};this.ymap.events.add(a,g);return r(this.ymap,a,g)},_on_zoom_changed:function(a,c,b){a=function(a){a.get("newZoom")!=a.get("oldZoom")&&c.call(b)};this.ymap.events.add("boundschange",a);return r(this.ymap,"boundschange",a)},_on_extent_changed:function(a,
c,b){this.ymap.events.add("boundschange",c,b);return r(this.ymap,"boundschange",c,b)},zoomTo:function(a){this.ymap.setBounds([[a[0],a[1]],[a[2]<180?a[2]:179.999,a[3]]])},destroy:function(){},enableLayer:function(a,c){if(e.isString(a)){var b=a.toLowerCase();b in f?c&&this.ymap.setType("yandex#"+f[b]):this.inherited(arguments)}else this.inherited(arguments)},getLayerModuleId:function(a){if(a.toLowerCase()in f)return null;return this.inherited(arguments)},_setCamera:function(a){this.ymap.setCenter(a.center,
a.zoom)},_set_center:function(a){this.ymap.setCenter(a)},_get_center:function(){return this.ymap.getCenter()},_set_zoom:function(a){this.ymap.setZoom(a)},_get_zoom:function(){return this.ymap.getZoom()},_get_extent:function(){var a=this.ymap.getBounds(),c=a[0],a=a[1];return[c[0],c[1],a[0],a[1]]},_appendDiv:function(a){this.map.container.children[0].appendChild(a)}})})},"dojo/_base/NodeList":function(){define("dojo/_base/NodeList",["./kernel","../query","./array","./html","../NodeList-dom"],function(b,
k,e){var k=k.NodeList,c=k.prototype;c.connect=k._adaptAsForEach(function(){return b.connect.apply(this,arguments)});c.coords=k._adaptAsMap(b.coords);k.events=["blur","focus","change","click","error","keydown","keypress","keyup","load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","submit"];e.forEach(k.events,function(b){var d="on"+b;c[d]=function(c,b){return this.connect(d,c,b)}});b.NodeList=k;return b.NodeList})},"djeo-ymaps/Placemark":function(){define("djeo-ymaps/Placemark",
["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Color","djeo/util/_base","djeo/common/Placemark"],function(b,k,e,c,l,d){function m(b,g,f,e){var b=d.get("stroke",g,f,e),a=d.get("strokeWidth",g,f,e),g=d.get("strokeOpacity",g,f,e);if(b||a!==void 0||g!==void 0){f={};if(b)f.strokeColor=(new c(b)).toHex();if(g!==void 0)f.strokeOpacity=g;if(a!==void 0)f.strokeWidth=a;return f}}function n(c,b){var d=b.match(/\b\w+\.\w{3,4}$/)[0],e=d.split("."),b=b.substr(0,b.length-e[0].length-e[1].length-
1)+e[0]+"_"+e[1]+"/"+d;return c.reg.url=b}var o=window.YMaps,b=b([d],{constructor:function(c){k.mixin(this,c)},makePoint:function(c,b){return new o.Placemark(b,{hasBalloon:!1,hideIconOnBalloonOpen:!1})},makeLineString:function(c,b){return this._makeLineString(b)},_makeLineString:function(c){return new o.Polyline(c,{hasBalloon:!1})},makePolygon:function(c,b){return this._makePolygon(b)},_makePolygon:function(c){return new o.Polygon(c,{hasBalloon:!1})},makeMultiLineString:function(c,b){var d=new o.GeoObjectCollection;
e.forEach(b,function(c){d.add(this._makeLineString(c))},this);return d},makeMultiPolygon:function(c,b){var d=new o.GeoObjectCollection;e.forEach(b,function(c){d.add(this._makePolygon(c))},this);return d},applyPointStyle:function(c,b){var f=b.point,e=d.getSpecificShapeStyle(b.points,this.specificStyleIndex),a=c.baseShapes[0],h=d.get("shape",b,f,e),o=d.getImgSrc(b,f,e),p=!0,m=d.getScale(b,f,e),w=a.options.get("iconImageHref"),i=c.orientation,y=c.map.simulateOrientation&&i!==void 0,s={};if(!h&&o)p=!1;
else if(!d.shapes[h]&&!w)h=d.defaultShapeType;var q=p?d.getSize(b,f,e):d.getImgSize(b,f,e);if(q)f=p?[q[0]/2,q[1]/2]:d.getAnchor(b,f,e,q),s.iconImageSize=[m*q[0],m*q[1]],s.iconImageOffset=[-m*f[0],-m*f[1]];else if(w&&(m=d.get("rScale",b,f,e),m!==void 0))q=a.options.get("iconImageSize"),f=a.options.get("iconImageOffset"),s.iconImageSize=[m*q[0],m*q[1]],s.iconImageOffset=[m*f[0],m*f[1]];h=this._getIconUrl(p,h,o);if(y){if(k.isObject(i))i=i.heading;i=Math.round(l.radToDeg(i));i<0&&(i=360+i);s.iconImageClipRect=
[[0,q[1]*i],[q[0],q[1]*(i+1)]];h&&(h=n(c,h))}if(h)s.iconImageHref=h;a.options.set(s)},applyLineStyle:function(c,b){var e=b.line,j=d.getSpecificShapeStyle(b.lines,this.specificStyleIndex),a=c.baseShapes[0];(e=m(a,b,e,j))&&a.options.set(e)},applyPolygonStyle:function(b,e){var f=e.polygon,j=b.baseShapes[0],a=d.get("fill",e,f),h=d.get("fillOpacity",e,f),f=m(j,e,f);if(a||h!==void 0){f=f||{};if(a)f.fillColor=(new c(a)).toHex();if(h!==void 0)f.fillOpacity=h}f&&j.options.set(f)},remove:function(){},show:function(c,
b){b?this.engine.ymap.geoObjects.add(c.baseShapes[0]):this.engine.ymap.geoObjects.remove(c.baseShapes[0])},makeText:function(){},setCoords:function(c,b){b.baseShapes[0].geometry.setCoordinates(c)},setOrientation:function(c,b){if(b.map.simulateOrientation){var d=b.baseShapes[0],e=Math.round(l.radToDeg(c)),a=d.options.get("iconImageSize"),h=b.reg.url;h||(h=n(b,d.options.get("iconImageHref")));e<0&&(e=360+e);d.options.set({iconImageHref:h,iconImageClipRect:[[0,a[1]*e],[a[0],a[1]*(e+1)]]})}}});b.init=
function(){o=ymaps};return b})},"djeo/_tiles":function(){define("djeo/_tiles",[],function(){var b=["WebTiles",{url:"http://[a,b,c].tile.openstreetmap.org"}];return{webtiles:["WebTiles",{}],roadmap:b,osm:b,openstreetmap:b,"osm.org":b,"openstreetmap.org":b,"mapquest-osm":["WebTiles",{url:"http://otile[1,2,3,4].mqcdn.com/tiles/1.0.0/osm"}],"mapquest-oa":["WebTiles",{url:"http://oatile[1,2,3,4].mqcdn.com/tiles/1.0.0/sat"}],arcgis_webtiles:["WebTiles",{}]}})},"dojo/main":function(){define("dojo/main",
["./_base/kernel","./has","require","./_base/sniff","./_base/lang","./_base/array","./ready","./_base/declare","./_base/connect","./_base/Deferred","./_base/json","./_base/Color","./has!dojo-firebug?./_firebug/firebug","./_base/browser","./_base/loader"],function(b,k,e,c,l,d,m){b.config.isDebug&&e(["./_firebug/firebug"]);var n=b.config.require;n&&(n=d.map(l.isArray(n)?n:[n],function(c){return c.replace(/\./g,"/")}),b.isAsync?e(n):m(1,function(){e(n)}));return b})},"djeo-ymaps/Navigation":function(){define("djeo-ymaps/Navigation",
["dojo/_base/declare"],function(b){function k(b){b.get("newZoom")!=b.get("oldZoom")&&this._onZoom()}return b(null,{enable:function(b){b===void 0&&(b=!0);var c=this.map.engine.ymap;b?(c.behaviors.enable(["drag","dblClickZoom","scrollZoom"]),c.events.add("boundschange",k,this)):(c.behaviors.disable(["scrollZoom","dblClickZoom","drag"]),c.events.remove("boundschange",k,this))}})})}}});define("djeo-ymaps/ymaps",[],1);